/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables;


import com.zenith.database.dto.Indexes;
import com.zenith.database.dto.Public;
import com.zenith.database.dto.enums.Connectiontype;
import com.zenith.database.dto.tables.records.ConnectionsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Connections extends TableImpl<ConnectionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.connections</code>
     */
    public static final Connections CONNECTIONS = new Connections();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConnectionsRecord> getRecordType() {
        return ConnectionsRecord.class;
    }

    /**
     * The column <code>public.connections.time</code>.
     */
    public final TableField<ConnectionsRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.connections.connection</code>.
     */
    public final TableField<ConnectionsRecord, Connectiontype> CONNECTION = createField(DSL.name("connection"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(Connectiontype.class), this, "");

    /**
     * The column <code>public.connections.player_name</code>.
     */
    public final TableField<ConnectionsRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.connections.player_uuid</code>.
     */
    public final TableField<ConnectionsRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID, this, "");

    private Connections(Name alias, Table<ConnectionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Connections(Name alias, Table<ConnectionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.connections</code> table reference
     */
    public Connections(String alias) {
        this(DSL.name(alias), CONNECTIONS);
    }

    /**
     * Create an aliased <code>public.connections</code> table reference
     */
    public Connections(Name alias) {
        this(alias, CONNECTIONS);
    }

    /**
     * Create a <code>public.connections</code> table reference
     */
    public Connections() {
        this(DSL.name("connections"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CONNECTIONS_PLAYER_UUID_IDX, Indexes.CONNECTIONS_TIME_IDX);
    }

    @Override
    public Connections as(String alias) {
        return new Connections(DSL.name(alias), this);
    }

    @Override
    public Connections as(Name alias) {
        return new Connections(alias, this);
    }

    @Override
    public Connections as(Table<?> alias) {
        return new Connections(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Connections rename(String name) {
        return new Connections(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Connections rename(Name name) {
        return new Connections(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Connections rename(Table<?> name) {
        return new Connections(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connections where(Condition condition) {
        return new Connections(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connections where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connections where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connections where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connections where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connections where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connections where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connections where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connections whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connections whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
