/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables;


import com.zenith.database.dto.Indexes;
import com.zenith.database.dto.Public;
import com.zenith.database.dto.tables.records.PlayercountRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playercount extends TableImpl<PlayercountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playercount</code>
     */
    public static final Playercount PLAYERCOUNT = new Playercount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayercountRecord> getRecordType() {
        return PlayercountRecord.class;
    }

    /**
     * The column <code>public.playercount.time</code>.
     */
    public final TableField<PlayercountRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.playercount.count</code>.
     */
    public final TableField<PlayercountRecord, Short> COUNT = createField(DSL.name("count"), SQLDataType.SMALLINT.nullable(false), this, "");

    private Playercount(Name alias, Table<PlayercountRecord> aliased) {
        this(alias, aliased, null);
    }

    private Playercount(Name alias, Table<PlayercountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.playercount</code> table reference
     */
    public Playercount(String alias) {
        this(DSL.name(alias), PLAYERCOUNT);
    }

    /**
     * Create an aliased <code>public.playercount</code> table reference
     */
    public Playercount(Name alias) {
        this(alias, PLAYERCOUNT);
    }

    /**
     * Create a <code>public.playercount</code> table reference
     */
    public Playercount() {
        this(DSL.name("playercount"), null);
    }

    public <O extends Record> Playercount(Table<O> child, ForeignKey<O, PlayercountRecord> key) {
        super(child, key, PLAYERCOUNT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYERCOUNT_TIME_IDX);
    }

    @Override
    public Playercount as(String alias) {
        return new Playercount(DSL.name(alias), this);
    }

    @Override
    public Playercount as(Name alias) {
        return new Playercount(alias, this);
    }

    @Override
    public Playercount as(Table<?> alias) {
        return new Playercount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Playercount rename(String name) {
        return new Playercount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playercount rename(Name name) {
        return new Playercount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playercount rename(Table<?> name) {
        return new Playercount(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<OffsetDateTime, Short> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super OffsetDateTime, ? super Short, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super OffsetDateTime, ? super Short, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
