/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables;


import com.zenith.database.dto.Indexes;
import com.zenith.database.dto.Public;
import com.zenith.database.dto.tables.records.QueuelengthRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Queuelength extends TableImpl<QueuelengthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.queuelength</code>
     */
    public static final Queuelength QUEUELENGTH = new Queuelength();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QueuelengthRecord> getRecordType() {
        return QueuelengthRecord.class;
    }

    /**
     * The column <code>public.queuelength.time</code>.
     */
    public final TableField<QueuelengthRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.queuelength.prio</code>.
     */
    public final TableField<QueuelengthRecord, Short> PRIO = createField(DSL.name("prio"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.queuelength.regular</code>.
     */
    public final TableField<QueuelengthRecord, Short> REGULAR = createField(DSL.name("regular"), SQLDataType.SMALLINT, this, "");

    private Queuelength(Name alias, Table<QueuelengthRecord> aliased) {
        this(alias, aliased, null);
    }

    private Queuelength(Name alias, Table<QueuelengthRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.queuelength</code> table reference
     */
    public Queuelength(String alias) {
        this(DSL.name(alias), QUEUELENGTH);
    }

    /**
     * Create an aliased <code>public.queuelength</code> table reference
     */
    public Queuelength(Name alias) {
        this(alias, QUEUELENGTH);
    }

    /**
     * Create a <code>public.queuelength</code> table reference
     */
    public Queuelength() {
        this(DSL.name("queuelength"), null);
    }

    public <O extends Record> Queuelength(Table<O> child, ForeignKey<O, QueuelengthRecord> key) {
        super(child, key, QUEUELENGTH);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.QUEUELENGTH_TIME_IDX);
    }

    @Override
    public Queuelength as(String alias) {
        return new Queuelength(DSL.name(alias), this);
    }

    @Override
    public Queuelength as(Name alias) {
        return new Queuelength(alias, this);
    }

    @Override
    public Queuelength as(Table<?> alias) {
        return new Queuelength(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Queuelength rename(String name) {
        return new Queuelength(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Queuelength rename(Name name) {
        return new Queuelength(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Queuelength rename(Table<?> name) {
        return new Queuelength(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<OffsetDateTime, Short, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super OffsetDateTime, ? super Short, ? super Short, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super OffsetDateTime, ? super Short, ? super Short, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
