/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables;


import com.zenith.database.dto.Indexes;
import com.zenith.database.dto.Keys;
import com.zenith.database.dto.Public;
import com.zenith.database.dto.tables.records.RestartsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Restarts extends TableImpl<RestartsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.restarts</code>
     */
    public static final Restarts RESTARTS = new Restarts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestartsRecord> getRecordType() {
        return RestartsRecord.class;
    }

    /**
     * The column <code>public.restarts.time</code>.
     */
    public final TableField<RestartsRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.restarts.id</code>.
     */
    public final TableField<RestartsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    private Restarts(Name alias, Table<RestartsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Restarts(Name alias, Table<RestartsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.restarts</code> table reference
     */
    public Restarts(String alias) {
        this(DSL.name(alias), RESTARTS);
    }

    /**
     * Create an aliased <code>public.restarts</code> table reference
     */
    public Restarts(Name alias) {
        this(alias, RESTARTS);
    }

    /**
     * Create a <code>public.restarts</code> table reference
     */
    public Restarts() {
        this(DSL.name("restarts"), null);
    }

    public <O extends Record> Restarts(Table<O> child, ForeignKey<O, RestartsRecord> key) {
        super(child, key, RESTARTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RESTARTS_TIME_IDX);
    }

    @Override
    public Identity<RestartsRecord, Integer> getIdentity() {
        return (Identity<RestartsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RestartsRecord> getPrimaryKey() {
        return Keys.RESTARTS_PKEY;
    }

    @Override
    public Restarts as(String alias) {
        return new Restarts(DSL.name(alias), this);
    }

    @Override
    public Restarts as(Name alias) {
        return new Restarts(alias, this);
    }

    @Override
    public Restarts as(Table<?> alias) {
        return new Restarts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Restarts rename(String name) {
        return new Restarts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restarts rename(Name name) {
        return new Restarts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restarts rename(Table<?> name) {
        return new Restarts(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<OffsetDateTime, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super OffsetDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super OffsetDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
