/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables;


import com.zenith.database.dto.Public;
import com.zenith.database.dto.tables.records.TablistRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.UUID;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tablist extends TableImpl<TablistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tablist</code>
     */
    public static final Tablist TABLIST = new Tablist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TablistRecord> getRecordType() {
        return TablistRecord.class;
    }

    /**
     * The column <code>public.tablist.player_name</code>.
     */
    public final TableField<TablistRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.tablist.player_uuid</code>.
     */
    public final TableField<TablistRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tablist.time</code>.
     */
    public final TableField<TablistRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Tablist(Name alias, Table<TablistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tablist(Name alias, Table<TablistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tablist</code> table reference
     */
    public Tablist(String alias) {
        this(DSL.name(alias), TABLIST);
    }

    /**
     * Create an aliased <code>public.tablist</code> table reference
     */
    public Tablist(Name alias) {
        this(alias, TABLIST);
    }

    /**
     * Create a <code>public.tablist</code> table reference
     */
    public Tablist() {
        this(DSL.name("tablist"), null);
    }

    public <O extends Record> Tablist(Table<O> child, ForeignKey<O, TablistRecord> key) {
        super(child, key, TABLIST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Tablist as(String alias) {
        return new Tablist(DSL.name(alias), this);
    }

    @Override
    public Tablist as(Name alias) {
        return new Tablist(alias, this);
    }

    @Override
    public Tablist as(Table<?> alias) {
        return new Tablist(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tablist rename(String name) {
        return new Tablist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tablist rename(Name name) {
        return new Tablist(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tablist rename(Table<?> name) {
        return new Tablist(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, UUID, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super UUID, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super UUID, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
