/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables;


import com.zenith.database.dto.Public;
import com.zenith.database.dto.tables.records.TablistRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tablist extends TableImpl<TablistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tablist</code>
     */
    public static final Tablist TABLIST = new Tablist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TablistRecord> getRecordType() {
        return TablistRecord.class;
    }

    /**
     * The column <code>public.tablist.player_name</code>.
     */
    public final TableField<TablistRecord, String> PLAYER_NAME = createField(DSL.name("player_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.tablist.player_uuid</code>.
     */
    public final TableField<TablistRecord, UUID> PLAYER_UUID = createField(DSL.name("player_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tablist.time</code>.
     */
    public final TableField<TablistRecord, OffsetDateTime> TIME = createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Tablist(Name alias, Table<TablistRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Tablist(Name alias, Table<TablistRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tablist</code> table reference
     */
    public Tablist(String alias) {
        this(DSL.name(alias), TABLIST);
    }

    /**
     * Create an aliased <code>public.tablist</code> table reference
     */
    public Tablist(Name alias) {
        this(alias, TABLIST);
    }

    /**
     * Create a <code>public.tablist</code> table reference
     */
    public Tablist() {
        this(DSL.name("tablist"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Tablist as(String alias) {
        return new Tablist(DSL.name(alias), this);
    }

    @Override
    public Tablist as(Name alias) {
        return new Tablist(alias, this);
    }

    @Override
    public Tablist as(Table<?> alias) {
        return new Tablist(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tablist rename(String name) {
        return new Tablist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tablist rename(Name name) {
        return new Tablist(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tablist rename(Table<?> name) {
        return new Tablist(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tablist where(Condition condition) {
        return new Tablist(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tablist where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tablist where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tablist where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tablist where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tablist where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tablist where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tablist where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tablist whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tablist whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
