// Auto-Generated by ZenithProxy Data Generator
package com.zenith.mc.biome;

import com.zenith.mc.DynamicRegistry;

import java.util.function.Supplier;

public final class BiomeRegistry {
    public static final DynamicRegistry<Biome> REGISTRY = new DynamicRegistry<Biome>(65);

    public static final Supplier<Biome> BADLANDS = () -> REGISTRY.get("badlands");

    public static final Supplier<Biome> BAMBOO_JUNGLE = () -> REGISTRY.get("bamboo_jungle");

    public static final Supplier<Biome> BASALT_DELTAS = () -> REGISTRY.get("basalt_deltas");

    public static final Supplier<Biome> BEACH = () -> REGISTRY.get("beach");

    public static final Supplier<Biome> BIRCH_FOREST = () -> REGISTRY.get("birch_forest");

    public static final Supplier<Biome> CHERRY_GROVE = () -> REGISTRY.get("cherry_grove");

    public static final Supplier<Biome> COLD_OCEAN = () -> REGISTRY.get("cold_ocean");

    public static final Supplier<Biome> CRIMSON_FOREST = () -> REGISTRY.get("crimson_forest");

    public static final Supplier<Biome> DARK_FOREST = () -> REGISTRY.get("dark_forest");

    public static final Supplier<Biome> DEEP_COLD_OCEAN = () -> REGISTRY.get("deep_cold_ocean");

    public static final Supplier<Biome> DEEP_DARK = () -> REGISTRY.get("deep_dark");

    public static final Supplier<Biome> DEEP_FROZEN_OCEAN = () -> REGISTRY.get("deep_frozen_ocean");

    public static final Supplier<Biome> DEEP_LUKEWARM_OCEAN = () -> REGISTRY.get("deep_lukewarm_ocean");

    public static final Supplier<Biome> DEEP_OCEAN = () -> REGISTRY.get("deep_ocean");

    public static final Supplier<Biome> DESERT = () -> REGISTRY.get("desert");

    public static final Supplier<Biome> DRIPSTONE_CAVES = () -> REGISTRY.get("dripstone_caves");

    public static final Supplier<Biome> END_BARRENS = () -> REGISTRY.get("end_barrens");

    public static final Supplier<Biome> END_HIGHLANDS = () -> REGISTRY.get("end_highlands");

    public static final Supplier<Biome> END_MIDLANDS = () -> REGISTRY.get("end_midlands");

    public static final Supplier<Biome> ERODED_BADLANDS = () -> REGISTRY.get("eroded_badlands");

    public static final Supplier<Biome> FLOWER_FOREST = () -> REGISTRY.get("flower_forest");

    public static final Supplier<Biome> FOREST = () -> REGISTRY.get("forest");

    public static final Supplier<Biome> FROZEN_OCEAN = () -> REGISTRY.get("frozen_ocean");

    public static final Supplier<Biome> FROZEN_PEAKS = () -> REGISTRY.get("frozen_peaks");

    public static final Supplier<Biome> FROZEN_RIVER = () -> REGISTRY.get("frozen_river");

    public static final Supplier<Biome> GROVE = () -> REGISTRY.get("grove");

    public static final Supplier<Biome> ICE_SPIKES = () -> REGISTRY.get("ice_spikes");

    public static final Supplier<Biome> JAGGED_PEAKS = () -> REGISTRY.get("jagged_peaks");

    public static final Supplier<Biome> JUNGLE = () -> REGISTRY.get("jungle");

    public static final Supplier<Biome> LUKEWARM_OCEAN = () -> REGISTRY.get("lukewarm_ocean");

    public static final Supplier<Biome> LUSH_CAVES = () -> REGISTRY.get("lush_caves");

    public static final Supplier<Biome> MANGROVE_SWAMP = () -> REGISTRY.get("mangrove_swamp");

    public static final Supplier<Biome> MEADOW = () -> REGISTRY.get("meadow");

    public static final Supplier<Biome> MUSHROOM_FIELDS = () -> REGISTRY.get("mushroom_fields");

    public static final Supplier<Biome> NETHER_WASTES = () -> REGISTRY.get("nether_wastes");

    public static final Supplier<Biome> OCEAN = () -> REGISTRY.get("ocean");

    public static final Supplier<Biome> OLD_GROWTH_BIRCH_FOREST = () -> REGISTRY.get("old_growth_birch_forest");

    public static final Supplier<Biome> OLD_GROWTH_PINE_TAIGA = () -> REGISTRY.get("old_growth_pine_taiga");

    public static final Supplier<Biome> OLD_GROWTH_SPRUCE_TAIGA = () -> REGISTRY.get("old_growth_spruce_taiga");

    public static final Supplier<Biome> PALE_GARDEN = () -> REGISTRY.get("pale_garden");

    public static final Supplier<Biome> PLAINS = () -> REGISTRY.get("plains");

    public static final Supplier<Biome> RIVER = () -> REGISTRY.get("river");

    public static final Supplier<Biome> SAVANNA = () -> REGISTRY.get("savanna");

    public static final Supplier<Biome> SAVANNA_PLATEAU = () -> REGISTRY.get("savanna_plateau");

    public static final Supplier<Biome> SMALL_END_ISLANDS = () -> REGISTRY.get("small_end_islands");

    public static final Supplier<Biome> SNOWY_BEACH = () -> REGISTRY.get("snowy_beach");

    public static final Supplier<Biome> SNOWY_PLAINS = () -> REGISTRY.get("snowy_plains");

    public static final Supplier<Biome> SNOWY_SLOPES = () -> REGISTRY.get("snowy_slopes");

    public static final Supplier<Biome> SNOWY_TAIGA = () -> REGISTRY.get("snowy_taiga");

    public static final Supplier<Biome> SOUL_SAND_VALLEY = () -> REGISTRY.get("soul_sand_valley");

    public static final Supplier<Biome> SPARSE_JUNGLE = () -> REGISTRY.get("sparse_jungle");

    public static final Supplier<Biome> STONY_PEAKS = () -> REGISTRY.get("stony_peaks");

    public static final Supplier<Biome> STONY_SHORE = () -> REGISTRY.get("stony_shore");

    public static final Supplier<Biome> SUNFLOWER_PLAINS = () -> REGISTRY.get("sunflower_plains");

    public static final Supplier<Biome> SWAMP = () -> REGISTRY.get("swamp");

    public static final Supplier<Biome> TAIGA = () -> REGISTRY.get("taiga");

    public static final Supplier<Biome> THE_END = () -> REGISTRY.get("the_end");

    public static final Supplier<Biome> THE_VOID = () -> REGISTRY.get("the_void");

    public static final Supplier<Biome> WARM_OCEAN = () -> REGISTRY.get("warm_ocean");

    public static final Supplier<Biome> WARPED_FOREST = () -> REGISTRY.get("warped_forest");

    public static final Supplier<Biome> WINDSWEPT_FOREST = () -> REGISTRY.get("windswept_forest");

    public static final Supplier<Biome> WINDSWEPT_GRAVELLY_HILLS = () -> REGISTRY.get("windswept_gravelly_hills");

    public static final Supplier<Biome> WINDSWEPT_HILLS = () -> REGISTRY.get("windswept_hills");

    public static final Supplier<Biome> WINDSWEPT_SAVANNA = () -> REGISTRY.get("windswept_savanna");

    public static final Supplier<Biome> WOODED_BADLANDS = () -> REGISTRY.get("wooded_badlands");

    static {
        REGISTRY.register(new Biome(0, "badlands"));
        REGISTRY.register(new Biome(1, "bamboo_jungle"));
        REGISTRY.register(new Biome(2, "basalt_deltas"));
        REGISTRY.register(new Biome(3, "beach"));
        REGISTRY.register(new Biome(4, "birch_forest"));
        REGISTRY.register(new Biome(5, "cherry_grove"));
        REGISTRY.register(new Biome(6, "cold_ocean"));
        REGISTRY.register(new Biome(7, "crimson_forest"));
        REGISTRY.register(new Biome(8, "dark_forest"));
        REGISTRY.register(new Biome(9, "deep_cold_ocean"));
        REGISTRY.register(new Biome(10, "deep_dark"));
        REGISTRY.register(new Biome(11, "deep_frozen_ocean"));
        REGISTRY.register(new Biome(12, "deep_lukewarm_ocean"));
        REGISTRY.register(new Biome(13, "deep_ocean"));
        REGISTRY.register(new Biome(14, "desert"));
        REGISTRY.register(new Biome(15, "dripstone_caves"));
        REGISTRY.register(new Biome(16, "end_barrens"));
        REGISTRY.register(new Biome(17, "end_highlands"));
        REGISTRY.register(new Biome(18, "end_midlands"));
        REGISTRY.register(new Biome(19, "eroded_badlands"));
        REGISTRY.register(new Biome(20, "flower_forest"));
        REGISTRY.register(new Biome(21, "forest"));
        REGISTRY.register(new Biome(22, "frozen_ocean"));
        REGISTRY.register(new Biome(23, "frozen_peaks"));
        REGISTRY.register(new Biome(24, "frozen_river"));
        REGISTRY.register(new Biome(25, "grove"));
        REGISTRY.register(new Biome(26, "ice_spikes"));
        REGISTRY.register(new Biome(27, "jagged_peaks"));
        REGISTRY.register(new Biome(28, "jungle"));
        REGISTRY.register(new Biome(29, "lukewarm_ocean"));
        REGISTRY.register(new Biome(30, "lush_caves"));
        REGISTRY.register(new Biome(31, "mangrove_swamp"));
        REGISTRY.register(new Biome(32, "meadow"));
        REGISTRY.register(new Biome(33, "mushroom_fields"));
        REGISTRY.register(new Biome(34, "nether_wastes"));
        REGISTRY.register(new Biome(35, "ocean"));
        REGISTRY.register(new Biome(36, "old_growth_birch_forest"));
        REGISTRY.register(new Biome(37, "old_growth_pine_taiga"));
        REGISTRY.register(new Biome(38, "old_growth_spruce_taiga"));
        REGISTRY.register(new Biome(39, "pale_garden"));
        REGISTRY.register(new Biome(40, "plains"));
        REGISTRY.register(new Biome(41, "river"));
        REGISTRY.register(new Biome(42, "savanna"));
        REGISTRY.register(new Biome(43, "savanna_plateau"));
        REGISTRY.register(new Biome(44, "small_end_islands"));
        REGISTRY.register(new Biome(45, "snowy_beach"));
        REGISTRY.register(new Biome(46, "snowy_plains"));
        REGISTRY.register(new Biome(47, "snowy_slopes"));
        REGISTRY.register(new Biome(48, "snowy_taiga"));
        REGISTRY.register(new Biome(49, "soul_sand_valley"));
        REGISTRY.register(new Biome(50, "sparse_jungle"));
        REGISTRY.register(new Biome(51, "stony_peaks"));
        REGISTRY.register(new Biome(52, "stony_shore"));
        REGISTRY.register(new Biome(53, "sunflower_plains"));
        REGISTRY.register(new Biome(54, "swamp"));
        REGISTRY.register(new Biome(55, "taiga"));
        REGISTRY.register(new Biome(56, "the_end"));
        REGISTRY.register(new Biome(57, "the_void"));
        REGISTRY.register(new Biome(58, "warm_ocean"));
        REGISTRY.register(new Biome(59, "warped_forest"));
        REGISTRY.register(new Biome(60, "windswept_forest"));
        REGISTRY.register(new Biome(61, "windswept_gravelly_hills"));
        REGISTRY.register(new Biome(62, "windswept_hills"));
        REGISTRY.register(new Biome(63, "windswept_savanna"));
        REGISTRY.register(new Biome(64, "wooded_badlands"));
    }
}
