/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import com.zenith.database.dto.enums.Connectiontype;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Connections implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final Connectiontype connection;
    private final String playerName;
    private final UUID playerUuid;

    public Connections(Connections value) {
        this.time = value.time;
        this.connection = value.connection;
        this.playerName = value.playerName;
        this.playerUuid = value.playerUuid;
    }

    public Connections(
            OffsetDateTime time,
            Connectiontype connection,
            String playerName,
            UUID playerUuid
    ) {
        this.time = time;
        this.connection = connection;
        this.playerName = playerName;
        this.playerUuid = playerUuid;
    }

    /**
     * Getter for <code>public.connections.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.connections.connection</code>.
     */
    public Connectiontype getConnection() {
        return this.connection;
    }

    /**
     * Getter for <code>public.connections.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Getter for <code>public.connections.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return this.playerUuid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Connections (");

        sb.append(time);
        sb.append(", ").append(connection);
        sb.append(", ").append(playerName);
        sb.append(", ").append(playerUuid);

        sb.append(")");
        return sb.toString();
    }
}
