/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ImportDeath implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final String deathMessage;
    private final String victimPlayerName;
    private final UUID victimPlayerUuid;
    private final String killerPlayerName;
    private final UUID killerPlayerUuid;
    private final String weaponName;
    private final String killerMob;

    public ImportDeath(ImportDeath value) {
        this.time = value.time;
        this.deathMessage = value.deathMessage;
        this.victimPlayerName = value.victimPlayerName;
        this.victimPlayerUuid = value.victimPlayerUuid;
        this.killerPlayerName = value.killerPlayerName;
        this.killerPlayerUuid = value.killerPlayerUuid;
        this.weaponName = value.weaponName;
        this.killerMob = value.killerMob;
    }

    public ImportDeath(
            OffsetDateTime time,
            String deathMessage,
            String victimPlayerName,
            UUID victimPlayerUuid,
            String killerPlayerName,
            UUID killerPlayerUuid,
            String weaponName,
            String killerMob
    ) {
        this.time = time;
        this.deathMessage = deathMessage;
        this.victimPlayerName = victimPlayerName;
        this.victimPlayerUuid = victimPlayerUuid;
        this.killerPlayerName = killerPlayerName;
        this.killerPlayerUuid = killerPlayerUuid;
        this.weaponName = weaponName;
        this.killerMob = killerMob;
    }

    /**
     * Getter for <code>public.import_death.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.import_death.death_message</code>.
     */
    public String getDeathMessage() {
        return this.deathMessage;
    }

    /**
     * Getter for <code>public.import_death.victim_player_name</code>.
     */
    public String getVictimPlayerName() {
        return this.victimPlayerName;
    }

    /**
     * Getter for <code>public.import_death.victim_player_uuid</code>.
     */
    public UUID getVictimPlayerUuid() {
        return this.victimPlayerUuid;
    }

    /**
     * Getter for <code>public.import_death.killer_player_name</code>.
     */
    public String getKillerPlayerName() {
        return this.killerPlayerName;
    }

    /**
     * Getter for <code>public.import_death.killer_player_uuid</code>.
     */
    public UUID getKillerPlayerUuid() {
        return this.killerPlayerUuid;
    }

    /**
     * Getter for <code>public.import_death.weapon_name</code>.
     */
    public String getWeaponName() {
        return this.weaponName;
    }

    /**
     * Getter for <code>public.import_death.killer_mob</code>.
     */
    public String getKillerMob() {
        return this.killerMob;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImportDeath (");

        sb.append(time);
        sb.append(", ").append(deathMessage);
        sb.append(", ").append(victimPlayerName);
        sb.append(", ").append(victimPlayerUuid);
        sb.append(", ").append(killerPlayerName);
        sb.append(", ").append(killerPlayerUuid);
        sb.append(", ").append(weaponName);
        sb.append(", ").append(killerMob);

        sb.append(")");
        return sb.toString();
    }
}
