/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playercount implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final Short count;

    public Playercount(Playercount value) {
        this.time = value.time;
        this.count = value.count;
    }

    public Playercount(
        OffsetDateTime time,
        Short count
    ) {
        this.time = time;
        this.count = count;
    }

    /**
     * Getter for <code>public.playercount.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.playercount.count</code>.
     */
    public Short getCount() {
        return this.count;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Playercount other = (Playercount) obj;
        if (this.time == null) {
            if (other.time != null)
                return false;
        }
        else if (!this.time.equals(other.time))
            return false;
        if (this.count == null) {
            if (other.count != null)
                return false;
        }
        else if (!this.count.equals(other.count))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.time == null) ? 0 : this.time.hashCode());
        result = prime * result + ((this.count == null) ? 0 : this.count.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Playercount (");

        sb.append(time);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
