/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Playercount implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final Short count;

    public Playercount(Playercount value) {
        this.time = value.time;
        this.count = value.count;
    }

    public Playercount(
            OffsetDateTime time,
            Short count
    ) {
        this.time = time;
        this.count = count;
    }

    /**
     * Getter for <code>public.playercount.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.playercount.count</code>.
     */
    public Short getCount() {
        return this.count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Playercount (");

        sb.append(time);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
