/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlaytimeAll implements Serializable {

    private static final long serialVersionUID = 1L;

    private final UUID pUuid;
    private final Integer playtime;

    public PlaytimeAll(PlaytimeAll value) {
        this.pUuid = value.pUuid;
        this.playtime = value.playtime;
    }

    public PlaytimeAll(
            UUID pUuid,
            Integer playtime
    ) {
        this.pUuid = pUuid;
        this.playtime = playtime;
    }

    /**
     * Getter for <code>public.playtime_all.p_uuid</code>.
     */
    public UUID getPUuid() {
        return this.pUuid;
    }

    /**
     * Getter for <code>public.playtime_all.playtime</code>.
     */
    public Integer getPlaytime() {
        return this.playtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlaytimeAll (");

        sb.append(pUuid);
        sb.append(", ").append(playtime);

        sb.append(")");
        return sb.toString();
    }
}
