/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Queuelength implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final Short prio;
    private final Short regular;

    public Queuelength(Queuelength value) {
        this.time = value.time;
        this.prio = value.prio;
        this.regular = value.regular;
    }

    public Queuelength(
        OffsetDateTime time,
        Short prio,
        Short regular
    ) {
        this.time = time;
        this.prio = prio;
        this.regular = regular;
    }

    /**
     * Getter for <code>public.queuelength.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.queuelength.prio</code>.
     */
    public Short getPrio() {
        return this.prio;
    }

    /**
     * Getter for <code>public.queuelength.regular</code>.
     */
    public Short getRegular() {
        return this.regular;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Queuelength other = (Queuelength) obj;
        if (this.time == null) {
            if (other.time != null)
                return false;
        }
        else if (!this.time.equals(other.time))
            return false;
        if (this.prio == null) {
            if (other.prio != null)
                return false;
        }
        else if (!this.prio.equals(other.prio))
            return false;
        if (this.regular == null) {
            if (other.regular != null)
                return false;
        }
        else if (!this.regular.equals(other.regular))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.time == null) ? 0 : this.time.hashCode());
        result = prime * result + ((this.prio == null) ? 0 : this.prio.hashCode());
        result = prime * result + ((this.regular == null) ? 0 : this.regular.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Queuelength (");

        sb.append(time);
        sb.append(", ").append(prio);
        sb.append(", ").append(regular);

        sb.append(")");
        return sb.toString();
    }
}
