/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Queuelength implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;
    private final Short prio;
    private final Short normal;

    public Queuelength(Queuelength value) {
        this.time = value.time;
        this.prio = value.prio;
        this.normal = value.normal;
    }

    public Queuelength(
            OffsetDateTime time,
            Short prio,
            Short normal
    ) {
        this.time = time;
        this.prio = prio;
        this.normal = normal;
    }

    /**
     * Getter for <code>public.queuelength.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    /**
     * Getter for <code>public.queuelength.prio</code>.
     */
    public Short getPrio() {
        return this.prio;
    }

    /**
     * Getter for <code>public.queuelength.normal</code>.
     */
    public Short getNormal() {
        return this.normal;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Queuelength (");

        sb.append(time);
        sb.append(", ").append(prio);
        sb.append(", ").append(normal);

        sb.append(")");
        return sb.toString();
    }
}
