/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Restarts implements Serializable {

    private static final long serialVersionUID = 1L;

    private final OffsetDateTime time;

    public Restarts(Restarts value) {
        this.time = value.time;
    }

    public Restarts(
            OffsetDateTime time
    ) {
        this.time = time;
    }

    /**
     * Getter for <code>public.restarts.time</code>.
     */
    public OffsetDateTime getTime() {
        return this.time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Restarts (");

        sb.append(time);

        sb.append(")");
        return sb.toString();
    }
}
