Args=-J--enable-native-access=ALL-UNNAMED \
  -J--sun-misc-unsafe-memory-access=allow \
  --features=com.zenith.util.graalvm.ReflectionFeature \
  -Duser.country=US \
  -Duser.language=en \
  --enable-url-protocols=https,http \
  -H:IncludeLocales=en \
  -H:+ReportExceptionStackTraces \
  --initialize-at-build-time=\
    com.google.common.collect,\
    com.google.common.collect.RegularImmutableList,\
    com.google.gson,\
    com.viaversion.nbt.mini,\
    com.viaversion.nbt.tag,\
    com.zenith.event,\
    com.zenith.feature.deathmessages,\
    com.zenith.mc,\
    com.zenith.terminal.ZenithComponentLoggerProvider,\
    com.zenith.util.struct,\
    it.unimi.dsi.fastutil,\
    net.kyori.adventure.key,\
    net.kyori.adventure.nbt,\
    net.kyori.adventure.text,\
    net.kyori.adventure.text.format.NamedTextColor,\
    net.kyori.adventure.util,\
    net.kyori.option,\
    org.cloudburstmc.math.immutable.vector.ImmutableVector3i,\
    org.geysermc.mcprotocollib.protocol.data.game.entity.attribute.ModifierOperation,\
    org.geysermc.mcprotocollib.protocol.data.game.entity.Effect,\
    org.geysermc.mcprotocollib.protocol.data.game.entity.EquipmentSlot,\
    org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType,\
    org.geysermc.mcprotocollib.protocol.data.game.inventory.ContainerType,\
    org.geysermc.mcprotocollib.protocol.data.game.item.component,\
    org.geysermc.mcprotocollib.protocol.data.game.item.ItemStack,\
    org.geysermc.mcprotocollib.protocol.data.game.level.block.BlockEntityType,\
    org.geysermc.mcprotocollib.protocol.data.game.level.sound.BuiltinSound \
  --initialize-at-run-time=\
    com.zenith.mc.MCGlobals,\
    sun.net.dns.ResolverConfigurationImpl
