// Auto-Generated by ZenithProxy Data Generator
package com.zenith.mc.entity;

import com.zenith.mc.Registry;

public final class EntityRegistry {
    public static final Registry<EntityData> REGISTRY = new Registry<EntityData>(149);

    public static final EntityData ACACIA_BOAT;

    public static final EntityData ACACIA_CHEST_BOAT;

    public static final EntityData ALLAY;

    public static final EntityData AREA_EFFECT_CLOUD;

    public static final EntityData ARMADILLO;

    public static final EntityData ARMOR_STAND;

    public static final EntityData ARROW;

    public static final EntityData AXOLOTL;

    public static final EntityData BAMBOO_CHEST_RAFT;

    public static final EntityData BAMBOO_RAFT;

    public static final EntityData BAT;

    public static final EntityData BEE;

    public static final EntityData BIRCH_BOAT;

    public static final EntityData BIRCH_CHEST_BOAT;

    public static final EntityData BLAZE;

    public static final EntityData BLOCK_DISPLAY;

    public static final EntityData BOGGED;

    public static final EntityData BREEZE;

    public static final EntityData BREEZE_WIND_CHARGE;

    public static final EntityData CAMEL;

    public static final EntityData CAT;

    public static final EntityData CAVE_SPIDER;

    public static final EntityData CHERRY_BOAT;

    public static final EntityData CHERRY_CHEST_BOAT;

    public static final EntityData CHEST_MINECART;

    public static final EntityData CHICKEN;

    public static final EntityData COD;

    public static final EntityData COMMAND_BLOCK_MINECART;

    public static final EntityData COW;

    public static final EntityData CREAKING;

    public static final EntityData CREEPER;

    public static final EntityData DARK_OAK_BOAT;

    public static final EntityData DARK_OAK_CHEST_BOAT;

    public static final EntityData DOLPHIN;

    public static final EntityData DONKEY;

    public static final EntityData DRAGON_FIREBALL;

    public static final EntityData DROWNED;

    public static final EntityData EGG;

    public static final EntityData ELDER_GUARDIAN;

    public static final EntityData ENDERMAN;

    public static final EntityData ENDERMITE;

    public static final EntityData ENDER_DRAGON;

    public static final EntityData ENDER_PEARL;

    public static final EntityData END_CRYSTAL;

    public static final EntityData EVOKER;

    public static final EntityData EVOKER_FANGS;

    public static final EntityData EXPERIENCE_BOTTLE;

    public static final EntityData EXPERIENCE_ORB;

    public static final EntityData EYE_OF_ENDER;

    public static final EntityData FALLING_BLOCK;

    public static final EntityData FIREBALL;

    public static final EntityData FIREWORK_ROCKET;

    public static final EntityData FOX;

    public static final EntityData FROG;

    public static final EntityData FURNACE_MINECART;

    public static final EntityData GHAST;

    public static final EntityData GIANT;

    public static final EntityData GLOW_ITEM_FRAME;

    public static final EntityData GLOW_SQUID;

    public static final EntityData GOAT;

    public static final EntityData GUARDIAN;

    public static final EntityData HOGLIN;

    public static final EntityData HOPPER_MINECART;

    public static final EntityData HORSE;

    public static final EntityData HUSK;

    public static final EntityData ILLUSIONER;

    public static final EntityData INTERACTION;

    public static final EntityData IRON_GOLEM;

    public static final EntityData ITEM;

    public static final EntityData ITEM_DISPLAY;

    public static final EntityData ITEM_FRAME;

    public static final EntityData JUNGLE_BOAT;

    public static final EntityData JUNGLE_CHEST_BOAT;

    public static final EntityData LEASH_KNOT;

    public static final EntityData LIGHTNING_BOLT;

    public static final EntityData LLAMA;

    public static final EntityData LLAMA_SPIT;

    public static final EntityData MAGMA_CUBE;

    public static final EntityData MANGROVE_BOAT;

    public static final EntityData MANGROVE_CHEST_BOAT;

    public static final EntityData MARKER;

    public static final EntityData MINECART;

    public static final EntityData MOOSHROOM;

    public static final EntityData MULE;

    public static final EntityData OAK_BOAT;

    public static final EntityData OAK_CHEST_BOAT;

    public static final EntityData OCELOT;

    public static final EntityData OMINOUS_ITEM_SPAWNER;

    public static final EntityData PAINTING;

    public static final EntityData PALE_OAK_BOAT;

    public static final EntityData PALE_OAK_CHEST_BOAT;

    public static final EntityData PANDA;

    public static final EntityData PARROT;

    public static final EntityData PHANTOM;

    public static final EntityData PIG;

    public static final EntityData PIGLIN;

    public static final EntityData PIGLIN_BRUTE;

    public static final EntityData PILLAGER;

    public static final EntityData POLAR_BEAR;

    public static final EntityData POTION;

    public static final EntityData PUFFERFISH;

    public static final EntityData RABBIT;

    public static final EntityData RAVAGER;

    public static final EntityData SALMON;

    public static final EntityData SHEEP;

    public static final EntityData SHULKER;

    public static final EntityData SHULKER_BULLET;

    public static final EntityData SILVERFISH;

    public static final EntityData SKELETON;

    public static final EntityData SKELETON_HORSE;

    public static final EntityData SLIME;

    public static final EntityData SMALL_FIREBALL;

    public static final EntityData SNIFFER;

    public static final EntityData SNOWBALL;

    public static final EntityData SNOW_GOLEM;

    public static final EntityData SPAWNER_MINECART;

    public static final EntityData SPECTRAL_ARROW;

    public static final EntityData SPIDER;

    public static final EntityData SPRUCE_BOAT;

    public static final EntityData SPRUCE_CHEST_BOAT;

    public static final EntityData SQUID;

    public static final EntityData STRAY;

    public static final EntityData STRIDER;

    public static final EntityData TADPOLE;

    public static final EntityData TEXT_DISPLAY;

    public static final EntityData TNT;

    public static final EntityData TNT_MINECART;

    public static final EntityData TRADER_LLAMA;

    public static final EntityData TRIDENT;

    public static final EntityData TROPICAL_FISH;

    public static final EntityData TURTLE;

    public static final EntityData VEX;

    public static final EntityData VILLAGER;

    public static final EntityData VINDICATOR;

    public static final EntityData WANDERING_TRADER;

    public static final EntityData WARDEN;

    public static final EntityData WIND_CHARGE;

    public static final EntityData WITCH;

    public static final EntityData WITHER;

    public static final EntityData WITHER_SKELETON;

    public static final EntityData WITHER_SKULL;

    public static final EntityData WOLF;

    public static final EntityData ZOGLIN;

    public static final EntityData ZOMBIE;

    public static final EntityData ZOMBIE_HORSE;

    public static final EntityData ZOMBIE_VILLAGER;

    public static final EntityData ZOMBIFIED_PIGLIN;

    public static final EntityData PLAYER;

    public static final EntityData FISHING_BOBBER;

    static {
        var jsonRegistrySpec = new EntityRegistrySpec();
        var data = jsonRegistrySpec.read();
        ACACIA_BOAT = REGISTRY.register(data.get(0));
        ACACIA_CHEST_BOAT = REGISTRY.register(data.get(1));
        ALLAY = REGISTRY.register(data.get(2));
        AREA_EFFECT_CLOUD = REGISTRY.register(data.get(3));
        ARMADILLO = REGISTRY.register(data.get(4));
        ARMOR_STAND = REGISTRY.register(data.get(5));
        ARROW = REGISTRY.register(data.get(6));
        AXOLOTL = REGISTRY.register(data.get(7));
        BAMBOO_CHEST_RAFT = REGISTRY.register(data.get(8));
        BAMBOO_RAFT = REGISTRY.register(data.get(9));
        BAT = REGISTRY.register(data.get(10));
        BEE = REGISTRY.register(data.get(11));
        BIRCH_BOAT = REGISTRY.register(data.get(12));
        BIRCH_CHEST_BOAT = REGISTRY.register(data.get(13));
        BLAZE = REGISTRY.register(data.get(14));
        BLOCK_DISPLAY = REGISTRY.register(data.get(15));
        BOGGED = REGISTRY.register(data.get(16));
        BREEZE = REGISTRY.register(data.get(17));
        BREEZE_WIND_CHARGE = REGISTRY.register(data.get(18));
        CAMEL = REGISTRY.register(data.get(19));
        CAT = REGISTRY.register(data.get(20));
        CAVE_SPIDER = REGISTRY.register(data.get(21));
        CHERRY_BOAT = REGISTRY.register(data.get(22));
        CHERRY_CHEST_BOAT = REGISTRY.register(data.get(23));
        CHEST_MINECART = REGISTRY.register(data.get(24));
        CHICKEN = REGISTRY.register(data.get(25));
        COD = REGISTRY.register(data.get(26));
        COMMAND_BLOCK_MINECART = REGISTRY.register(data.get(27));
        COW = REGISTRY.register(data.get(28));
        CREAKING = REGISTRY.register(data.get(29));
        CREEPER = REGISTRY.register(data.get(30));
        DARK_OAK_BOAT = REGISTRY.register(data.get(31));
        DARK_OAK_CHEST_BOAT = REGISTRY.register(data.get(32));
        DOLPHIN = REGISTRY.register(data.get(33));
        DONKEY = REGISTRY.register(data.get(34));
        DRAGON_FIREBALL = REGISTRY.register(data.get(35));
        DROWNED = REGISTRY.register(data.get(36));
        EGG = REGISTRY.register(data.get(37));
        ELDER_GUARDIAN = REGISTRY.register(data.get(38));
        ENDERMAN = REGISTRY.register(data.get(39));
        ENDERMITE = REGISTRY.register(data.get(40));
        ENDER_DRAGON = REGISTRY.register(data.get(41));
        ENDER_PEARL = REGISTRY.register(data.get(42));
        END_CRYSTAL = REGISTRY.register(data.get(43));
        EVOKER = REGISTRY.register(data.get(44));
        EVOKER_FANGS = REGISTRY.register(data.get(45));
        EXPERIENCE_BOTTLE = REGISTRY.register(data.get(46));
        EXPERIENCE_ORB = REGISTRY.register(data.get(47));
        EYE_OF_ENDER = REGISTRY.register(data.get(48));
        FALLING_BLOCK = REGISTRY.register(data.get(49));
        FIREBALL = REGISTRY.register(data.get(50));
        FIREWORK_ROCKET = REGISTRY.register(data.get(51));
        FOX = REGISTRY.register(data.get(52));
        FROG = REGISTRY.register(data.get(53));
        FURNACE_MINECART = REGISTRY.register(data.get(54));
        GHAST = REGISTRY.register(data.get(55));
        GIANT = REGISTRY.register(data.get(56));
        GLOW_ITEM_FRAME = REGISTRY.register(data.get(57));
        GLOW_SQUID = REGISTRY.register(data.get(58));
        GOAT = REGISTRY.register(data.get(59));
        GUARDIAN = REGISTRY.register(data.get(60));
        HOGLIN = REGISTRY.register(data.get(61));
        HOPPER_MINECART = REGISTRY.register(data.get(62));
        HORSE = REGISTRY.register(data.get(63));
        HUSK = REGISTRY.register(data.get(64));
        ILLUSIONER = REGISTRY.register(data.get(65));
        INTERACTION = REGISTRY.register(data.get(66));
        IRON_GOLEM = REGISTRY.register(data.get(67));
        ITEM = REGISTRY.register(data.get(68));
        ITEM_DISPLAY = REGISTRY.register(data.get(69));
        ITEM_FRAME = REGISTRY.register(data.get(70));
        JUNGLE_BOAT = REGISTRY.register(data.get(71));
        JUNGLE_CHEST_BOAT = REGISTRY.register(data.get(72));
        LEASH_KNOT = REGISTRY.register(data.get(73));
        LIGHTNING_BOLT = REGISTRY.register(data.get(74));
        LLAMA = REGISTRY.register(data.get(75));
        LLAMA_SPIT = REGISTRY.register(data.get(76));
        MAGMA_CUBE = REGISTRY.register(data.get(77));
        MANGROVE_BOAT = REGISTRY.register(data.get(78));
        MANGROVE_CHEST_BOAT = REGISTRY.register(data.get(79));
        MARKER = REGISTRY.register(data.get(80));
        MINECART = REGISTRY.register(data.get(81));
        MOOSHROOM = REGISTRY.register(data.get(82));
        MULE = REGISTRY.register(data.get(83));
        OAK_BOAT = REGISTRY.register(data.get(84));
        OAK_CHEST_BOAT = REGISTRY.register(data.get(85));
        OCELOT = REGISTRY.register(data.get(86));
        OMINOUS_ITEM_SPAWNER = REGISTRY.register(data.get(87));
        PAINTING = REGISTRY.register(data.get(88));
        PALE_OAK_BOAT = REGISTRY.register(data.get(89));
        PALE_OAK_CHEST_BOAT = REGISTRY.register(data.get(90));
        PANDA = REGISTRY.register(data.get(91));
        PARROT = REGISTRY.register(data.get(92));
        PHANTOM = REGISTRY.register(data.get(93));
        PIG = REGISTRY.register(data.get(94));
        PIGLIN = REGISTRY.register(data.get(95));
        PIGLIN_BRUTE = REGISTRY.register(data.get(96));
        PILLAGER = REGISTRY.register(data.get(97));
        POLAR_BEAR = REGISTRY.register(data.get(98));
        POTION = REGISTRY.register(data.get(99));
        PUFFERFISH = REGISTRY.register(data.get(100));
        RABBIT = REGISTRY.register(data.get(101));
        RAVAGER = REGISTRY.register(data.get(102));
        SALMON = REGISTRY.register(data.get(103));
        SHEEP = REGISTRY.register(data.get(104));
        SHULKER = REGISTRY.register(data.get(105));
        SHULKER_BULLET = REGISTRY.register(data.get(106));
        SILVERFISH = REGISTRY.register(data.get(107));
        SKELETON = REGISTRY.register(data.get(108));
        SKELETON_HORSE = REGISTRY.register(data.get(109));
        SLIME = REGISTRY.register(data.get(110));
        SMALL_FIREBALL = REGISTRY.register(data.get(111));
        SNIFFER = REGISTRY.register(data.get(112));
        SNOWBALL = REGISTRY.register(data.get(113));
        SNOW_GOLEM = REGISTRY.register(data.get(114));
        SPAWNER_MINECART = REGISTRY.register(data.get(115));
        SPECTRAL_ARROW = REGISTRY.register(data.get(116));
        SPIDER = REGISTRY.register(data.get(117));
        SPRUCE_BOAT = REGISTRY.register(data.get(118));
        SPRUCE_CHEST_BOAT = REGISTRY.register(data.get(119));
        SQUID = REGISTRY.register(data.get(120));
        STRAY = REGISTRY.register(data.get(121));
        STRIDER = REGISTRY.register(data.get(122));
        TADPOLE = REGISTRY.register(data.get(123));
        TEXT_DISPLAY = REGISTRY.register(data.get(124));
        TNT = REGISTRY.register(data.get(125));
        TNT_MINECART = REGISTRY.register(data.get(126));
        TRADER_LLAMA = REGISTRY.register(data.get(127));
        TRIDENT = REGISTRY.register(data.get(128));
        TROPICAL_FISH = REGISTRY.register(data.get(129));
        TURTLE = REGISTRY.register(data.get(130));
        VEX = REGISTRY.register(data.get(131));
        VILLAGER = REGISTRY.register(data.get(132));
        VINDICATOR = REGISTRY.register(data.get(133));
        WANDERING_TRADER = REGISTRY.register(data.get(134));
        WARDEN = REGISTRY.register(data.get(135));
        WIND_CHARGE = REGISTRY.register(data.get(136));
        WITCH = REGISTRY.register(data.get(137));
        WITHER = REGISTRY.register(data.get(138));
        WITHER_SKELETON = REGISTRY.register(data.get(139));
        WITHER_SKULL = REGISTRY.register(data.get(140));
        WOLF = REGISTRY.register(data.get(141));
        ZOGLIN = REGISTRY.register(data.get(142));
        ZOMBIE = REGISTRY.register(data.get(143));
        ZOMBIE_HORSE = REGISTRY.register(data.get(144));
        ZOMBIE_VILLAGER = REGISTRY.register(data.get(145));
        ZOMBIFIED_PIGLIN = REGISTRY.register(data.get(146));
        PLAYER = REGISTRY.register(data.get(147));
        FISHING_BOBBER = REGISTRY.register(data.get(148));
    }
}
