// Auto-Generated by ZenithProxy Data Generator
package com.zenith.mc.entity;

import com.zenith.mc.Registry;
import org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType;

public final class EntityRegistry {
    public static final Registry<EntityData> REGISTRY = new Registry<EntityData>(126);

    public static final EntityData ALLAY = REGISTRY.register(new EntityData(0, "allay", 0.35f, 0.6f, EntityType.ALLAY));

    public static final EntityData AREA_EFFECT_CLOUD = REGISTRY.register(new EntityData(1, "area_effect_cloud", 6.0f, 0.5f, EntityType.AREA_EFFECT_CLOUD));

    public static final EntityData ARMOR_STAND = REGISTRY.register(new EntityData(2, "armor_stand", 0.5f, 1.975f, EntityType.ARMOR_STAND));

    public static final EntityData ARROW = REGISTRY.register(new EntityData(3, "arrow", 0.5f, 0.5f, EntityType.ARROW));

    public static final EntityData AXOLOTL = REGISTRY.register(new EntityData(4, "axolotl", 0.75f, 0.42f, EntityType.AXOLOTL));

    public static final EntityData BAT = REGISTRY.register(new EntityData(5, "bat", 0.5f, 0.9f, EntityType.BAT));

    public static final EntityData BEE = REGISTRY.register(new EntityData(6, "bee", 0.7f, 0.6f, EntityType.BEE));

    public static final EntityData BLAZE = REGISTRY.register(new EntityData(7, "blaze", 0.6f, 1.8f, EntityType.BLAZE));

    public static final EntityData BLOCK_DISPLAY = REGISTRY.register(new EntityData(8, "block_display", 0.0f, 0.0f, EntityType.BLOCK_DISPLAY));

    public static final EntityData BOAT = REGISTRY.register(new EntityData(9, "boat", 1.375f, 0.5625f, EntityType.BOAT));

    public static final EntityData BREEZE = REGISTRY.register(new EntityData(10, "breeze", 0.6f, 1.7f, EntityType.BREEZE));

    public static final EntityData CAMEL = REGISTRY.register(new EntityData(11, "camel", 1.7f, 2.375f, EntityType.CAMEL));

    public static final EntityData CAT = REGISTRY.register(new EntityData(12, "cat", 0.6f, 0.7f, EntityType.CAT));

    public static final EntityData CAVE_SPIDER = REGISTRY.register(new EntityData(13, "cave_spider", 0.7f, 0.5f, EntityType.CAVE_SPIDER));

    public static final EntityData CHEST_BOAT = REGISTRY.register(new EntityData(14, "chest_boat", 1.375f, 0.5625f, EntityType.CHEST_BOAT));

    public static final EntityData CHEST_MINECART = REGISTRY.register(new EntityData(15, "chest_minecart", 0.98f, 0.7f, EntityType.CHEST_MINECART));

    public static final EntityData CHICKEN = REGISTRY.register(new EntityData(16, "chicken", 0.4f, 0.7f, EntityType.CHICKEN));

    public static final EntityData COD = REGISTRY.register(new EntityData(17, "cod", 0.5f, 0.3f, EntityType.COD));

    public static final EntityData COMMAND_BLOCK_MINECART = REGISTRY.register(new EntityData(18, "command_block_minecart", 0.98f, 0.7f, EntityType.COMMAND_BLOCK_MINECART));

    public static final EntityData COW = REGISTRY.register(new EntityData(19, "cow", 0.9f, 1.4f, EntityType.COW));

    public static final EntityData CREEPER = REGISTRY.register(new EntityData(20, "creeper", 0.6f, 1.7f, EntityType.CREEPER));

    public static final EntityData DOLPHIN = REGISTRY.register(new EntityData(21, "dolphin", 0.9f, 0.6f, EntityType.DOLPHIN));

    public static final EntityData DONKEY = REGISTRY.register(new EntityData(22, "donkey", 1.3964844f, 1.5f, EntityType.DONKEY));

    public static final EntityData DRAGON_FIREBALL = REGISTRY.register(new EntityData(23, "dragon_fireball", 1.0f, 1.0f, EntityType.DRAGON_FIREBALL));

    public static final EntityData DROWNED = REGISTRY.register(new EntityData(24, "drowned", 0.6f, 1.95f, EntityType.DROWNED));

    public static final EntityData EGG = REGISTRY.register(new EntityData(25, "egg", 0.25f, 0.25f, EntityType.EGG));

    public static final EntityData ELDER_GUARDIAN = REGISTRY.register(new EntityData(26, "elder_guardian", 1.9975f, 1.9975f, EntityType.ELDER_GUARDIAN));

    public static final EntityData END_CRYSTAL = REGISTRY.register(new EntityData(27, "end_crystal", 2.0f, 2.0f, EntityType.END_CRYSTAL));

    public static final EntityData ENDER_DRAGON = REGISTRY.register(new EntityData(28, "ender_dragon", 16.0f, 8.0f, EntityType.ENDER_DRAGON));

    public static final EntityData ENDER_PEARL = REGISTRY.register(new EntityData(29, "ender_pearl", 0.25f, 0.25f, EntityType.ENDER_PEARL));

    public static final EntityData ENDERMAN = REGISTRY.register(new EntityData(30, "enderman", 0.6f, 2.9f, EntityType.ENDERMAN));

    public static final EntityData ENDERMITE = REGISTRY.register(new EntityData(31, "endermite", 0.4f, 0.3f, EntityType.ENDERMITE));

    public static final EntityData EVOKER = REGISTRY.register(new EntityData(32, "evoker", 0.6f, 1.95f, EntityType.EVOKER));

    public static final EntityData EVOKER_FANGS = REGISTRY.register(new EntityData(33, "evoker_fangs", 0.5f, 0.8f, EntityType.EVOKER_FANGS));

    public static final EntityData EXPERIENCE_BOTTLE = REGISTRY.register(new EntityData(34, "experience_bottle", 0.25f, 0.25f, EntityType.EXPERIENCE_BOTTLE));

    public static final EntityData EXPERIENCE_ORB = REGISTRY.register(new EntityData(35, "experience_orb", 0.5f, 0.5f, EntityType.EXPERIENCE_ORB));

    public static final EntityData EYE_OF_ENDER = REGISTRY.register(new EntityData(36, "eye_of_ender", 0.25f, 0.25f, EntityType.EYE_OF_ENDER));

    public static final EntityData FALLING_BLOCK = REGISTRY.register(new EntityData(37, "falling_block", 0.98f, 0.98f, EntityType.FALLING_BLOCK));

    public static final EntityData FIREWORK_ROCKET = REGISTRY.register(new EntityData(38, "firework_rocket", 0.25f, 0.25f, EntityType.FIREWORK_ROCKET));

    public static final EntityData FOX = REGISTRY.register(new EntityData(39, "fox", 0.6f, 0.7f, EntityType.FOX));

    public static final EntityData FROG = REGISTRY.register(new EntityData(40, "frog", 0.5f, 0.5f, EntityType.FROG));

    public static final EntityData FURNACE_MINECART = REGISTRY.register(new EntityData(41, "furnace_minecart", 0.98f, 0.7f, EntityType.FURNACE_MINECART));

    public static final EntityData GHAST = REGISTRY.register(new EntityData(42, "ghast", 4.0f, 4.0f, EntityType.GHAST));

    public static final EntityData GIANT = REGISTRY.register(new EntityData(43, "giant", 3.6f, 12.0f, EntityType.GIANT));

    public static final EntityData GLOW_ITEM_FRAME = REGISTRY.register(new EntityData(44, "glow_item_frame", 0.5f, 0.5f, EntityType.GLOW_ITEM_FRAME));

    public static final EntityData GLOW_SQUID = REGISTRY.register(new EntityData(45, "glow_squid", 0.8f, 0.8f, EntityType.GLOW_SQUID));

    public static final EntityData GOAT = REGISTRY.register(new EntityData(46, "goat", 0.9f, 1.3f, EntityType.GOAT));

    public static final EntityData GUARDIAN = REGISTRY.register(new EntityData(47, "guardian", 0.85f, 0.85f, EntityType.GUARDIAN));

    public static final EntityData HOGLIN = REGISTRY.register(new EntityData(48, "hoglin", 1.3964844f, 1.4f, EntityType.HOGLIN));

    public static final EntityData HOPPER_MINECART = REGISTRY.register(new EntityData(49, "hopper_minecart", 0.98f, 0.7f, EntityType.HOPPER_MINECART));

    public static final EntityData HORSE = REGISTRY.register(new EntityData(50, "horse", 1.3964844f, 1.6f, EntityType.HORSE));

    public static final EntityData HUSK = REGISTRY.register(new EntityData(51, "husk", 0.6f, 1.95f, EntityType.HUSK));

    public static final EntityData ILLUSIONER = REGISTRY.register(new EntityData(52, "illusioner", 0.6f, 1.95f, EntityType.ILLUSIONER));

    public static final EntityData INTERACTION = REGISTRY.register(new EntityData(53, "interaction", 0.0f, 0.0f, EntityType.INTERACTION));

    public static final EntityData IRON_GOLEM = REGISTRY.register(new EntityData(54, "iron_golem", 1.4f, 2.7f, EntityType.IRON_GOLEM));

    public static final EntityData ITEM = REGISTRY.register(new EntityData(55, "item", 0.25f, 0.25f, EntityType.ITEM));

    public static final EntityData ITEM_DISPLAY = REGISTRY.register(new EntityData(56, "item_display", 0.0f, 0.0f, EntityType.ITEM_DISPLAY));

    public static final EntityData ITEM_FRAME = REGISTRY.register(new EntityData(57, "item_frame", 0.5f, 0.5f, EntityType.ITEM_FRAME));

    public static final EntityData FIREBALL = REGISTRY.register(new EntityData(58, "fireball", 1.0f, 1.0f, EntityType.FIREBALL));

    public static final EntityData LEASH_KNOT = REGISTRY.register(new EntityData(59, "leash_knot", 0.375f, 0.5f, EntityType.LEASH_KNOT));

    public static final EntityData LIGHTNING_BOLT = REGISTRY.register(new EntityData(60, "lightning_bolt", 0.0f, 0.0f, EntityType.LIGHTNING_BOLT));

    public static final EntityData LLAMA = REGISTRY.register(new EntityData(61, "llama", 0.9f, 1.87f, EntityType.LLAMA));

    public static final EntityData LLAMA_SPIT = REGISTRY.register(new EntityData(62, "llama_spit", 0.25f, 0.25f, EntityType.LLAMA_SPIT));

    public static final EntityData MAGMA_CUBE = REGISTRY.register(new EntityData(63, "magma_cube", 2.04f, 2.04f, EntityType.MAGMA_CUBE));

    public static final EntityData MARKER = REGISTRY.register(new EntityData(64, "marker", 0.0f, 0.0f, EntityType.MARKER));

    public static final EntityData MINECART = REGISTRY.register(new EntityData(65, "minecart", 0.98f, 0.7f, EntityType.MINECART));

    public static final EntityData MOOSHROOM = REGISTRY.register(new EntityData(66, "mooshroom", 0.9f, 1.4f, EntityType.MOOSHROOM));

    public static final EntityData MULE = REGISTRY.register(new EntityData(67, "mule", 1.3964844f, 1.6f, EntityType.MULE));

    public static final EntityData OCELOT = REGISTRY.register(new EntityData(68, "ocelot", 0.6f, 0.7f, EntityType.OCELOT));

    public static final EntityData PAINTING = REGISTRY.register(new EntityData(69, "painting", 0.5f, 0.5f, EntityType.PAINTING));

    public static final EntityData PANDA = REGISTRY.register(new EntityData(70, "panda", 1.3f, 1.25f, EntityType.PANDA));

    public static final EntityData PARROT = REGISTRY.register(new EntityData(71, "parrot", 0.5f, 0.9f, EntityType.PARROT));

    public static final EntityData PHANTOM = REGISTRY.register(new EntityData(72, "phantom", 0.9f, 0.5f, EntityType.PHANTOM));

    public static final EntityData PIG = REGISTRY.register(new EntityData(73, "pig", 0.9f, 0.9f, EntityType.PIG));

    public static final EntityData PIGLIN = REGISTRY.register(new EntityData(74, "piglin", 0.6f, 1.95f, EntityType.PIGLIN));

    public static final EntityData PIGLIN_BRUTE = REGISTRY.register(new EntityData(75, "piglin_brute", 0.6f, 1.95f, EntityType.PIGLIN_BRUTE));

    public static final EntityData PILLAGER = REGISTRY.register(new EntityData(76, "pillager", 0.6f, 1.95f, EntityType.PILLAGER));

    public static final EntityData POLAR_BEAR = REGISTRY.register(new EntityData(77, "polar_bear", 1.4f, 1.4f, EntityType.POLAR_BEAR));

    public static final EntityData POTION = REGISTRY.register(new EntityData(78, "potion", 0.25f, 0.25f, EntityType.POTION));

    public static final EntityData PUFFERFISH = REGISTRY.register(new EntityData(79, "pufferfish", 0.7f, 0.7f, EntityType.PUFFERFISH));

    public static final EntityData RABBIT = REGISTRY.register(new EntityData(80, "rabbit", 0.4f, 0.5f, EntityType.RABBIT));

    public static final EntityData RAVAGER = REGISTRY.register(new EntityData(81, "ravager", 1.95f, 2.2f, EntityType.RAVAGER));

    public static final EntityData SALMON = REGISTRY.register(new EntityData(82, "salmon", 0.7f, 0.4f, EntityType.SALMON));

    public static final EntityData SHEEP = REGISTRY.register(new EntityData(83, "sheep", 0.9f, 1.3f, EntityType.SHEEP));

    public static final EntityData SHULKER = REGISTRY.register(new EntityData(84, "shulker", 1.0f, 1.0f, EntityType.SHULKER));

    public static final EntityData SHULKER_BULLET = REGISTRY.register(new EntityData(85, "shulker_bullet", 0.3125f, 0.3125f, EntityType.SHULKER_BULLET));

    public static final EntityData SILVERFISH = REGISTRY.register(new EntityData(86, "silverfish", 0.4f, 0.3f, EntityType.SILVERFISH));

    public static final EntityData SKELETON = REGISTRY.register(new EntityData(87, "skeleton", 0.6f, 1.99f, EntityType.SKELETON));

    public static final EntityData SKELETON_HORSE = REGISTRY.register(new EntityData(88, "skeleton_horse", 1.3964844f, 1.6f, EntityType.SKELETON_HORSE));

    public static final EntityData SLIME = REGISTRY.register(new EntityData(89, "slime", 2.04f, 2.04f, EntityType.SLIME));

    public static final EntityData SMALL_FIREBALL = REGISTRY.register(new EntityData(90, "small_fireball", 0.3125f, 0.3125f, EntityType.SMALL_FIREBALL));

    public static final EntityData SNIFFER = REGISTRY.register(new EntityData(91, "sniffer", 1.9f, 1.75f, EntityType.SNIFFER));

    public static final EntityData SNOW_GOLEM = REGISTRY.register(new EntityData(92, "snow_golem", 0.7f, 1.9f, EntityType.SNOW_GOLEM));

    public static final EntityData SNOWBALL = REGISTRY.register(new EntityData(93, "snowball", 0.25f, 0.25f, EntityType.SNOWBALL));

    public static final EntityData SPAWNER_MINECART = REGISTRY.register(new EntityData(94, "spawner_minecart", 0.98f, 0.7f, EntityType.SPAWNER_MINECART));

    public static final EntityData SPECTRAL_ARROW = REGISTRY.register(new EntityData(95, "spectral_arrow", 0.5f, 0.5f, EntityType.SPECTRAL_ARROW));

    public static final EntityData SPIDER = REGISTRY.register(new EntityData(96, "spider", 1.4f, 0.9f, EntityType.SPIDER));

    public static final EntityData SQUID = REGISTRY.register(new EntityData(97, "squid", 0.8f, 0.8f, EntityType.SQUID));

    public static final EntityData STRAY = REGISTRY.register(new EntityData(98, "stray", 0.6f, 1.99f, EntityType.STRAY));

    public static final EntityData STRIDER = REGISTRY.register(new EntityData(99, "strider", 0.9f, 1.7f, EntityType.STRIDER));

    public static final EntityData TADPOLE = REGISTRY.register(new EntityData(100, "tadpole", 0.4f, 0.3f, EntityType.TADPOLE));

    public static final EntityData TEXT_DISPLAY = REGISTRY.register(new EntityData(101, "text_display", 0.0f, 0.0f, EntityType.TEXT_DISPLAY));

    public static final EntityData TNT = REGISTRY.register(new EntityData(102, "tnt", 0.98f, 0.98f, EntityType.TNT));

    public static final EntityData TNT_MINECART = REGISTRY.register(new EntityData(103, "tnt_minecart", 0.98f, 0.7f, EntityType.TNT_MINECART));

    public static final EntityData TRADER_LLAMA = REGISTRY.register(new EntityData(104, "trader_llama", 0.9f, 1.87f, EntityType.TRADER_LLAMA));

    public static final EntityData TRIDENT = REGISTRY.register(new EntityData(105, "trident", 0.5f, 0.5f, EntityType.TRIDENT));

    public static final EntityData TROPICAL_FISH = REGISTRY.register(new EntityData(106, "tropical_fish", 0.5f, 0.4f, EntityType.TROPICAL_FISH));

    public static final EntityData TURTLE = REGISTRY.register(new EntityData(107, "turtle", 1.2f, 0.4f, EntityType.TURTLE));

    public static final EntityData VEX = REGISTRY.register(new EntityData(108, "vex", 0.4f, 0.8f, EntityType.VEX));

    public static final EntityData VILLAGER = REGISTRY.register(new EntityData(109, "villager", 0.6f, 1.95f, EntityType.VILLAGER));

    public static final EntityData VINDICATOR = REGISTRY.register(new EntityData(110, "vindicator", 0.6f, 1.95f, EntityType.VINDICATOR));

    public static final EntityData WANDERING_TRADER = REGISTRY.register(new EntityData(111, "wandering_trader", 0.6f, 1.95f, EntityType.WANDERING_TRADER));

    public static final EntityData WARDEN = REGISTRY.register(new EntityData(112, "warden", 0.9f, 2.9f, EntityType.WARDEN));

    public static final EntityData WIND_CHARGE = REGISTRY.register(new EntityData(113, "wind_charge", 0.3125f, 0.3125f, EntityType.WIND_CHARGE));

    public static final EntityData WITCH = REGISTRY.register(new EntityData(114, "witch", 0.6f, 1.95f, EntityType.WITCH));

    public static final EntityData WITHER = REGISTRY.register(new EntityData(115, "wither", 0.9f, 3.5f, EntityType.WITHER));

    public static final EntityData WITHER_SKELETON = REGISTRY.register(new EntityData(116, "wither_skeleton", 0.7f, 2.4f, EntityType.WITHER_SKELETON));

    public static final EntityData WITHER_SKULL = REGISTRY.register(new EntityData(117, "wither_skull", 0.3125f, 0.3125f, EntityType.WITHER_SKULL));

    public static final EntityData WOLF = REGISTRY.register(new EntityData(118, "wolf", 0.6f, 0.85f, EntityType.WOLF));

    public static final EntityData ZOGLIN = REGISTRY.register(new EntityData(119, "zoglin", 1.3964844f, 1.4f, EntityType.ZOGLIN));

    public static final EntityData ZOMBIE = REGISTRY.register(new EntityData(120, "zombie", 0.6f, 1.95f, EntityType.ZOMBIE));

    public static final EntityData ZOMBIE_HORSE = REGISTRY.register(new EntityData(121, "zombie_horse", 1.3964844f, 1.6f, EntityType.ZOMBIE_HORSE));

    public static final EntityData ZOMBIE_VILLAGER = REGISTRY.register(new EntityData(122, "zombie_villager", 0.6f, 1.95f, EntityType.ZOMBIE_VILLAGER));

    public static final EntityData ZOMBIFIED_PIGLIN = REGISTRY.register(new EntityData(123, "zombified_piglin", 0.6f, 1.95f, EntityType.ZOMBIFIED_PIGLIN));

    public static final EntityData PLAYER = REGISTRY.register(new EntityData(124, "player", 0.6f, 1.8f, EntityType.PLAYER));

    public static final EntityData FISHING_BOBBER = REGISTRY.register(new EntityData(125, "fishing_bobber", 0.25f, 0.25f, EntityType.FISHING_BOBBER));
}
