/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Chats;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChatsRecord extends TableRecordImpl<ChatsRecord> implements Record4<OffsetDateTime, String, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(OffsetDateTime time, String chat, String playerName, UUID playerUuid) {
        super(Chats.CHATS);

        setTime(time);
        setChat(chat);
        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
    }

    /**
     * Getter for <code>public.chats.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.chats.time</code>.
     */
    public ChatsRecord setTime(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.chat</code>.
     */
    public String getChat() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.chats.chat</code>.
     */
    public ChatsRecord setChat(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.chats.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.chats.player_name</code>.
     */
    public ChatsRecord setPlayerName(String value) {
        set(2, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.chats.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.chats.player_uuid</code>.
     */
    public ChatsRecord setPlayerUuid(UUID value) {
        set(3, value);
        return this;
    }

    @Override
    public Row4<OffsetDateTime, String, String, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<OffsetDateTime, String, String, UUID> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<OffsetDateTime> field1() {
        return Chats.CHATS.TIME;
    }

    @Override
    public Field<String> field2() {
        return Chats.CHATS.CHAT;
    }

    @Override
    public Field<String> field3() {
        return Chats.CHATS.PLAYER_NAME;
    }

    @Override
    public Field<UUID> field4() {
        return Chats.CHATS.PLAYER_UUID;
    }

    @Override
    public OffsetDateTime component1() {
        return getTime();
    }

    @Override
    public String component2() {
        return getChat();
    }

    @Override
    public String component3() {
        return getPlayerName();
    }

    @Override
    public UUID component4() {
        return getPlayerUuid();
    }

    @Override
    public OffsetDateTime value1() {
        return getTime();
    }

    @Override
    public String value2() {
        return getChat();
    }

    @Override
    public String value3() {
        return getPlayerName();
    }

    @Override
    public UUID value4() {
        return getPlayerUuid();
    }

    @Override
    public ChatsRecord value1(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public ChatsRecord value2(String value) {
        setChat(value);
        return this;
    }

    @Override
    public ChatsRecord value3(String value) {
        setPlayerName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public ChatsRecord value4(UUID value) {
        setPlayerUuid(value);
        return this;
    }

    @Override
    public ChatsRecord values(OffsetDateTime value1, String value2, String value3, UUID value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
