/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Deaths;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DeathsRecord extends TableRecordImpl<DeathsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.deaths.time</code>.
     */
    public DeathsRecord setTime(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.deaths.death_message</code>.
     */
    public DeathsRecord setDeathMessage(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.death_message</code>.
     */
    public String getDeathMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.deaths.victim_player_name</code>.
     */
    public DeathsRecord setVictimPlayerName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.victim_player_name</code>.
     */
    public String getVictimPlayerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.deaths.victim_player_uuid</code>.
     */
    public DeathsRecord setVictimPlayerUuid(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.victim_player_uuid</code>.
     */
    public UUID getVictimPlayerUuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.deaths.killer_player_name</code>.
     */
    public DeathsRecord setKillerPlayerName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.killer_player_name</code>.
     */
    public String getKillerPlayerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.deaths.killer_player_uuid</code>.
     */
    public DeathsRecord setKillerPlayerUuid(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.killer_player_uuid</code>.
     */
    public UUID getKillerPlayerUuid() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.deaths.weapon_name</code>.
     */
    public DeathsRecord setWeaponName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.weapon_name</code>.
     */
    public String getWeaponName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.deaths.killer_mob</code>.
     */
    public DeathsRecord setKillerMob(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.deaths.killer_mob</code>.
     */
    public String getKillerMob() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeathsRecord
     */
    public DeathsRecord() {
        super(Deaths.DEATHS);
    }

    /**
     * Create a detached, initialised DeathsRecord
     */
    public DeathsRecord(OffsetDateTime time, String deathMessage, String victimPlayerName, UUID victimPlayerUuid, String killerPlayerName, UUID killerPlayerUuid, String weaponName, String killerMob) {
        super(Deaths.DEATHS);

        setTime(time);
        setDeathMessage(deathMessage);
        setVictimPlayerName(victimPlayerName);
        setVictimPlayerUuid(victimPlayerUuid);
        setKillerPlayerName(killerPlayerName);
        setKillerPlayerUuid(killerPlayerUuid);
        setWeaponName(weaponName);
        setKillerMob(killerMob);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DeathsRecord
     */
    public DeathsRecord(com.zenith.database.dto.tables.pojos.Deaths value) {
        super(Deaths.DEATHS);

        if (value != null) {
            setTime(value.getTime());
            setDeathMessage(value.getDeathMessage());
            setVictimPlayerName(value.getVictimPlayerName());
            setVictimPlayerUuid(value.getVictimPlayerUuid());
            setKillerPlayerName(value.getKillerPlayerName());
            setKillerPlayerUuid(value.getKillerPlayerUuid());
            setWeaponName(value.getWeaponName());
            setKillerMob(value.getKillerMob());
            resetChangedOnNotNull();
        }
    }
}
