/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Names;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NamesRecord extends TableRecordImpl<NamesRecord> implements Record4<String, UUID, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.names.name</code>.
     */
    public NamesRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Create a detached NamesRecord
     */
    public NamesRecord() {
        super(Names.NAMES);
    }

    /**
     * Setter for <code>public.names.uuid</code>.
     */
    public NamesRecord setUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Create a detached, initialised NamesRecord
     */
    public NamesRecord(String name, UUID uuid, OffsetDateTime changedtoat, OffsetDateTime changedfromat) {
        super(Names.NAMES);

        setName(name);
        setUuid(uuid);
        setChangedtoat(changedtoat);
        setChangedfromat(changedfromat);
    }

    /**
     * Getter for <code>public.names.changedtoat</code>.
     */
    public OffsetDateTime getChangedtoat() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Getter for <code>public.names.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.names.changedtoat</code>.
     */
    public NamesRecord setChangedtoat(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.names.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, UUID, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, UUID, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Names.NAMES.NAME;
    }

    @Override
    public Field<UUID> field2() {
        return Names.NAMES.UUID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Names.NAMES.CHANGEDTOAT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Names.NAMES.CHANGEDFROMAT;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public UUID component2() {
        return getUuid();
    }

    @Override
    public OffsetDateTime component3() {
        return getChangedtoat();
    }

    @Override
    public OffsetDateTime component4() {
        return getChangedfromat();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public UUID value2() {
        return getUuid();
    }

    @Override
    public OffsetDateTime value3() {
        return getChangedtoat();
    }

    @Override
    public OffsetDateTime value4() {
        return getChangedfromat();
    }

    @Override
    public NamesRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public NamesRecord value2(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public NamesRecord value3(OffsetDateTime value) {
        setChangedtoat(value);
        return this;
    }

    @Override
    public NamesRecord value4(OffsetDateTime value) {
        setChangedfromat(value);
        return this;
    }

    @Override
    public NamesRecord values(String value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.names.changedfromat</code>.
     */
    public OffsetDateTime getChangedfromat() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.names.changedfromat</code>.
     */
    public NamesRecord setChangedfromat(OffsetDateTime value) {
        set(3, value);
        return this;
    }
}
