/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Playercount;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayercountRecord extends TableRecordImpl<PlayercountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playercount.time</code>.
     */
    public PlayercountRecord setTime(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.playercount.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.playercount.count</code>.
     */
    public PlayercountRecord setCount(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.playercount.count</code>.
     */
    public Short getCount() {
        return (Short) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayercountRecord
     */
    public PlayercountRecord() {
        super(Playercount.PLAYERCOUNT);
    }

    /**
     * Create a detached, initialised PlayercountRecord
     */
    public PlayercountRecord(OffsetDateTime time, Short count) {
        super(Playercount.PLAYERCOUNT);

        setTime(time);
        setCount(count);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlayercountRecord
     */
    public PlayercountRecord(com.zenith.database.dto.tables.pojos.Playercount value) {
        super(Playercount.PLAYERCOUNT);

        if (value != null) {
            setTime(value.getTime());
            setCount(value.getCount());
            resetChangedOnNotNull();
        }
    }
}
