/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Queuelength;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QueuelengthRecord extends TableRecordImpl<QueuelengthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.queuelength.time</code>.
     */
    public QueuelengthRecord setTime(OffsetDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.queuelength.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>public.queuelength.prio</code>.
     */
    public QueuelengthRecord setPrio(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.queuelength.prio</code>.
     */
    public Short getPrio() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.queuelength.regular</code>.
     */
    public QueuelengthRecord setRegular(Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.queuelength.regular</code>.
     */
    public Short getRegular() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueuelengthRecord
     */
    public QueuelengthRecord() {
        super(Queuelength.QUEUELENGTH);
    }

    /**
     * Create a detached, initialised QueuelengthRecord
     */
    public QueuelengthRecord(OffsetDateTime time, Short prio, Short regular) {
        super(Queuelength.QUEUELENGTH);

        setTime(time);
        setPrio(prio);
        setRegular(regular);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QueuelengthRecord
     */
    public QueuelengthRecord(com.zenith.database.dto.tables.pojos.Queuelength value) {
        super(Queuelength.QUEUELENGTH);

        if (value != null) {
            setTime(value.getTime());
            setPrio(value.getPrio());
            setRegular(value.getRegular());
            resetChangedOnNotNull();
        }
    }
}
