/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Queuewait;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QueuewaitRecord extends TableRecordImpl<QueuewaitRecord> implements Record7<Integer, String, Boolean, OffsetDateTime, OffsetDateTime, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.queuewait.id</code>.
     */
    public QueuewaitRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.queuewait.player_name</code>.
     */
    public QueuewaitRecord setPlayerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.queuewait.prio</code>.
     */
    public QueuewaitRecord setPrio(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.prio</code>.
     */
    public Boolean getPrio() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.queuewait.start_queue_time</code>.
     */
    public QueuewaitRecord setStartQueueTime(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.start_queue_time</code>.
     */
    public OffsetDateTime getStartQueueTime() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.queuewait.end_queue_time</code>.
     */
    public QueuewaitRecord setEndQueueTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.end_queue_time</code>.
     */
    public OffsetDateTime getEndQueueTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.queuewait.queue_time</code>.
     */
    public QueuewaitRecord setQueueTime(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.queue_time</code>.
     */
    public Long getQueueTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.queuewait.initial_queue_len</code>.
     */
    public QueuewaitRecord setInitialQueueLen(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.initial_queue_len</code>.
     */
    public Integer getInitialQueueLen() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, Boolean, OffsetDateTime, OffsetDateTime, Long, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, Boolean, OffsetDateTime, OffsetDateTime, Long, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Queuewait.QUEUEWAIT.ID;
    }

    @Override
    public Field<String> field2() {
        return Queuewait.QUEUEWAIT.PLAYER_NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return Queuewait.QUEUEWAIT.PRIO;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Queuewait.QUEUEWAIT.START_QUEUE_TIME;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Queuewait.QUEUEWAIT.END_QUEUE_TIME;
    }

    @Override
    public Field<Long> field6() {
        return Queuewait.QUEUEWAIT.QUEUE_TIME;
    }

    @Override
    public Field<Integer> field7() {
        return Queuewait.QUEUEWAIT.INITIAL_QUEUE_LEN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPlayerName();
    }

    @Override
    public Boolean component3() {
        return getPrio();
    }

    @Override
    public OffsetDateTime component4() {
        return getStartQueueTime();
    }

    @Override
    public OffsetDateTime component5() {
        return getEndQueueTime();
    }

    @Override
    public Long component6() {
        return getQueueTime();
    }

    @Override
    public Integer component7() {
        return getInitialQueueLen();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPlayerName();
    }

    @Override
    public Boolean value3() {
        return getPrio();
    }

    @Override
    public OffsetDateTime value4() {
        return getStartQueueTime();
    }

    @Override
    public OffsetDateTime value5() {
        return getEndQueueTime();
    }

    @Override
    public Long value6() {
        return getQueueTime();
    }

    @Override
    public Integer value7() {
        return getInitialQueueLen();
    }

    @Override
    public QueuewaitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public QueuewaitRecord value2(String value) {
        setPlayerName(value);
        return this;
    }

    @Override
    public QueuewaitRecord value3(Boolean value) {
        setPrio(value);
        return this;
    }

    @Override
    public QueuewaitRecord value4(OffsetDateTime value) {
        setStartQueueTime(value);
        return this;
    }

    @Override
    public QueuewaitRecord value5(OffsetDateTime value) {
        setEndQueueTime(value);
        return this;
    }

    @Override
    public QueuewaitRecord value6(Long value) {
        setQueueTime(value);
        return this;
    }

    @Override
    public QueuewaitRecord value7(Integer value) {
        setInitialQueueLen(value);
        return this;
    }

    @Override
    public QueuewaitRecord values(Integer value1, String value2, Boolean value3, OffsetDateTime value4, OffsetDateTime value5, Long value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueuewaitRecord
     */
    public QueuewaitRecord() {
        super(Queuewait.QUEUEWAIT);
    }

    /**
     * Create a detached, initialised QueuewaitRecord
     */
    public QueuewaitRecord(Integer id, String playerName, Boolean prio, OffsetDateTime startQueueTime, OffsetDateTime endQueueTime, Long queueTime, Integer initialQueueLen) {
        super(Queuewait.QUEUEWAIT);

        setId(id);
        setPlayerName(playerName);
        setPrio(prio);
        setStartQueueTime(startQueueTime);
        setEndQueueTime(endQueueTime);
        setQueueTime(queueTime);
        setInitialQueueLen(initialQueueLen);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QueuewaitRecord
     */
    public QueuewaitRecord(com.zenith.database.dto.tables.pojos.Queuewait value) {
        super(Queuewait.QUEUEWAIT);

        if (value != null) {
            setId(value.getId());
            setPlayerName(value.getPlayerName());
            setPrio(value.getPrio());
            setStartQueueTime(value.getStartQueueTime());
            setEndQueueTime(value.getEndQueueTime());
            setQueueTime(value.getQueueTime());
            setInitialQueueLen(value.getInitialQueueLen());
            resetChangedOnNotNull();
        }
    }
}
