/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Queuewait;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QueuewaitRecord extends TableRecordImpl<QueuewaitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.queuewait.id</code>.
     */
    public QueuewaitRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.queuewait.player_name</code>.
     */
    public QueuewaitRecord setPlayerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.queuewait.prio</code>.
     */
    public QueuewaitRecord setPrio(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.prio</code>.
     */
    public Boolean getPrio() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.queuewait.start_queue_time</code>.
     */
    public QueuewaitRecord setStartQueueTime(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.start_queue_time</code>.
     */
    public OffsetDateTime getStartQueueTime() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.queuewait.end_queue_time</code>.
     */
    public QueuewaitRecord setEndQueueTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.end_queue_time</code>.
     */
    public OffsetDateTime getEndQueueTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.queuewait.queue_time</code>.
     */
    public QueuewaitRecord setQueueTime(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.queue_time</code>.
     */
    public Long getQueueTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.queuewait.initial_queue_len</code>.
     */
    public QueuewaitRecord setInitialQueueLen(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.queuewait.initial_queue_len</code>.
     */
    public Integer getInitialQueueLen() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueuewaitRecord
     */
    public QueuewaitRecord() {
        super(Queuewait.QUEUEWAIT);
    }

    /**
     * Create a detached, initialised QueuewaitRecord
     */
    public QueuewaitRecord(Integer id, String playerName, Boolean prio, OffsetDateTime startQueueTime, OffsetDateTime endQueueTime, Long queueTime, Integer initialQueueLen) {
        super(Queuewait.QUEUEWAIT);

        setId(id);
        setPlayerName(playerName);
        setPrio(prio);
        setStartQueueTime(startQueueTime);
        setEndQueueTime(endQueueTime);
        setQueueTime(queueTime);
        setInitialQueueLen(initialQueueLen);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QueuewaitRecord
     */
    public QueuewaitRecord(com.zenith.database.dto.tables.pojos.Queuewait value) {
        super(Queuewait.QUEUEWAIT);

        if (value != null) {
            setId(value.getId());
            setPlayerName(value.getPlayerName());
            setPrio(value.getPrio());
            setStartQueueTime(value.getStartQueueTime());
            setEndQueueTime(value.getEndQueueTime());
            setQueueTime(value.getQueueTime());
            setInitialQueueLen(value.getInitialQueueLen());
            resetChangedOnNotNull();
        }
    }
}
