/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Tablist;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablistRecord extends TableRecordImpl<TablistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tablist.player_name</code>.
     */
    public TablistRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.tablist.player_uuid</code>.
     */
    public TablistRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tablist.time</code>.
     */
    public TablistRecord setTime(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablistRecord
     */
    public TablistRecord() {
        super(Tablist.TABLIST);
    }

    /**
     * Create a detached, initialised TablistRecord
     */
    public TablistRecord(String playerName, UUID playerUuid, OffsetDateTime time) {
        super(Tablist.TABLIST);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TablistRecord
     */
    public TablistRecord(com.zenith.database.dto.tables.pojos.Tablist value) {
        super(Tablist.TABLIST);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }
}
