/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.tables.records;


import com.zenith.database.dto.tables.Tablist;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablistRecord extends TableRecordImpl<TablistRecord> implements Record3<String, UUID, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tablist.player_name</code>.
     */
    public TablistRecord setPlayerName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.tablist.player_uuid</code>.
     */
    public TablistRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tablist.time</code>.
     */
    public TablistRecord setTime(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tablist.time</code>.
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, UUID, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, UUID, OffsetDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Tablist.TABLIST.PLAYER_NAME;
    }

    @Override
    public Field<UUID> field2() {
        return Tablist.TABLIST.PLAYER_UUID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Tablist.TABLIST.TIME;
    }

    @Override
    public String component1() {
        return getPlayerName();
    }

    @Override
    public UUID component2() {
        return getPlayerUuid();
    }

    @Override
    public OffsetDateTime component3() {
        return getTime();
    }

    @Override
    public String value1() {
        return getPlayerName();
    }

    @Override
    public UUID value2() {
        return getPlayerUuid();
    }

    @Override
    public OffsetDateTime value3() {
        return getTime();
    }

    @Override
    public TablistRecord value1(String value) {
        setPlayerName(value);
        return this;
    }

    @Override
    public TablistRecord value2(UUID value) {
        setPlayerUuid(value);
        return this;
    }

    @Override
    public TablistRecord value3(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public TablistRecord values(String value1, UUID value2, OffsetDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablistRecord
     */
    public TablistRecord() {
        super(Tablist.TABLIST);
    }

    /**
     * Create a detached, initialised TablistRecord
     */
    public TablistRecord(String playerName, UUID playerUuid, OffsetDateTime time) {
        super(Tablist.TABLIST);

        setPlayerName(playerName);
        setPlayerUuid(playerUuid);
        setTime(time);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TablistRecord
     */
    public TablistRecord(com.zenith.database.dto.tables.pojos.Tablist value) {
        super(Tablist.TABLIST);

        if (value != null) {
            setPlayerName(value.getPlayerName());
            setPlayerUuid(value.getPlayerUuid());
            setTime(value.getTime());
            resetChangedOnNotNull();
        }
    }
}
