/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto;


import com.zenith.database.dto.tables.Restarts;
import com.zenith.database.dto.tables.records.RestartsRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RestartsRecord> RESTARTS_PKEY = Internal.createUniqueKey(Restarts.RESTARTS, DSL.name("restarts_pkey"), new TableField[] { Restarts.RESTARTS.ID }, true);
}
