/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto;


import com.zenith.database.dto.tables.*;
import com.zenith.database.dto.tables.records.PlaytimeAllRecord;
import org.jooq.Configuration;
import org.jooq.Result;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.chats</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>public.connections</code>.
     */
    public static final Connections CONNECTIONS = Connections.CONNECTIONS;

    /**
     * The table <code>public.deaths</code>.
     */
    public static final Deaths DEATHS = Deaths.DEATHS;

    /**
     * The table <code>public.names</code>.
     */
    public static final Names NAMES = Names.NAMES;

    /**
     * The table <code>public.playercount</code>.
     */
    public static final Playercount PLAYERCOUNT = Playercount.PLAYERCOUNT;

    /**
     * The table <code>public.playtime_all</code>.
     */
    public static final PlaytimeAll PLAYTIME_ALL = PlaytimeAll.PLAYTIME_ALL;

    /**
     * Call <code>public.playtime_all</code>.
     */
    public static Result<PlaytimeAllRecord> PLAYTIME_ALL(
            Configuration configuration
    ) {
        return configuration.dsl().selectFrom(com.zenith.database.dto.tables.PlaytimeAll.PLAYTIME_ALL.call(
        )).fetch();
    }

    /**
     * Get <code>public.playtime_all</code> as a table.
     */
    public static PlaytimeAll PLAYTIME_ALL() {
        return com.zenith.database.dto.tables.PlaytimeAll.PLAYTIME_ALL.call(
        );
    }

    /**
     * The table <code>public.queuelength</code>.
     */
    public static final Queuelength QUEUELENGTH = Queuelength.QUEUELENGTH;

    /**
     * The table <code>public.queuewait</code>.
     */
    public static final Queuewait QUEUEWAIT = Queuewait.QUEUEWAIT;

    /**
     * The table <code>public.restarts</code>.
     */
    public static final Restarts RESTARTS = Restarts.RESTARTS;
}
