package com.zenith.generator;

import com.squareup.javapoet.*;
import com.zenith.DataGenerator;
import com.zenith.mc.Registry;
import com.zenith.mc.RegistryData;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

public abstract class RegistryGenerator<T extends RegistryData> implements Generator {
    protected final Class<T> dataType;
    protected final String classPackage;
    protected final String registryClassName;

    public RegistryGenerator(
        Class<T> dataType,
        String classPackage,
        String registryClassName
    ) {
        this.dataType = dataType;
        this.classPackage = classPackage;
        this.registryClassName = registryClassName;
    }

    public abstract List<T> buildDataList();
    public abstract CodeBlock dataInitializer(T data);

    @Override
    public void generate() {
        List<T> dataList = buildDataList();

        ParameterizedTypeName registryType = ParameterizedTypeName.get(Registry.class, dataType);
        var registryField = FieldSpec
            .builder(registryType, "REGISTRY")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
            .initializer("new $T(" + dataList.size() + ")", registryType)
            .build();

        var dataInstanceFields = dataList.stream()
            .map(dataInstance -> FieldSpec.builder(dataType, dataInstance.name().toUpperCase())
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer(CodeBlock.builder()
                                 .add("$N.register($L)", registryField, dataInitializer(dataInstance))
                                 .build())
                .build())
            .toList();

        var typeSpec = TypeSpec.classBuilder(registryClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addField(registryField)
            .addFields(dataInstanceFields)
            .build();
        var javaFile = JavaFile
            .builder(classPackage, typeSpec)
            .indent("    ")
            .addFileComment("Auto-Generated by ZenithProxy Data Generator")
            .build();
        try {
            javaFile.writeTo(DataGenerator.dataDir);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        DataGenerator.LOG.info("{} generated with {} instances!", registryClassName, dataList.size());
    }

}
