/*
 * This file is generated by jOOQ.
 */
package com.zenith.database.dto.enums;


import com.zenith.database.dto.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public enum Connectiontype implements EnumType {

    JOIN("JOIN"),

    LEAVE("LEAVE");

    private final String literal;

    private Connectiontype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "connectiontype";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
