name: Build Launcher

# Command:

# act workflow_dispatch -W .github\workflows\act-build-launcher.yml --artifact-server-path build\artifacts

on:
  workflow_dispatch:

env:
  UV_PYTHON: '3.14.4'
  pyinstaller_version: "6.19.0"

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-20.04' ]
        include:
          - os: 'ubuntu-20.04'
            artifact-name: 'launcher-linux-amd64'
            move-command: 'mv dist/__main__ dist/launch'
            zip-command: 'zip -j dist/ZenithProxy-launcher-linux-amd64.zip dist/launch'
            sha1-command: 'sha1sum -b dist/launch | cut -d" " -f 1'
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install PyInstaller
        run: |
          uv tool install pyinstaller@${{ env.pyinstaller_version }}

      - name: Build launcher
        run: >
          uv tool run --with-requirements src/launcher/requirements.txt --upgrade
          pyinstaller@${{ env.pyinstaller_version }} --specpath ./build
          -p ./src/launcher --onefile
          --runtime-tmpdir .launcher.tmp
          --noconfirm
          -i ../src/launcher/icon.ico
          ./src/launcher/__main__.py

      - name: Rename executable
        run: |
          ${{ matrix.move-command }}

      - name: Create zip
        run: |
          ${{ matrix.zip-command }}

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/ZenithProxy-${{ matrix.artifact-name }}.zip
          if-no-files-found: error

      - name: Get Binary Hash
        run: ${{ matrix.sha1-command }} > ZenithProxy-${{ matrix.artifact-name }}.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}.sha1
          path: ZenithProxy-${{ matrix.artifact-name }}.sha1
          if-no-files-found: error

  build-alpine:
    env:
      pyinstaller_version: "6.18.0"
      UV_PYTHON: '3.14.2'
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image || '' }}
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest']
        include:
          - os: 'ubuntu-latest'
            image: 'node:24-alpine3.23'
            artifact-name: 'launcher-alpine-amd64'
            sha1-command: 'sha1sum -b dist/launch | cut -d" " -f 1'
    steps:
      - name: Install Deps
        run: apk add zip bash build-base ca-certificates curl gcc git libc-dev libffi-dev libgcc make musl-dev openssl openssl-dev zlib-dev

      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install PyInstaller
        run: |
          uv tool install pyinstaller@${{ env.pyinstaller_version }}

      - name: Build launcher
        run: >
          uv tool run --with-requirements src/launcher/requirements.txt --upgrade
          pyinstaller@${{ env.pyinstaller_version }} --specpath ./build
          -p ./src/launcher --onefile
          --runtime-tmpdir .launcher.tmp
          --noconfirm
          -i ../src/launcher/icon.ico
          ./src/launcher/__main__.py

      - name: Rename executable
        run: |
          mv dist/__main__ dist/launch

      - name: Create zip
        run: |
          zip -j dist/ZenithProxy-${{ matrix.artifact-name }}.zip dist/launch

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/ZenithProxy-${{ matrix.artifact-name }}.zip
          if-no-files-found: error

      - name: Get Binary Hash
        run: ${{ matrix.sha1-command }} > ZenithProxy-${{ matrix.artifact-name }}.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}.sha1
          path: ZenithProxy-${{ matrix.artifact-name }}.sha1
          if-no-files-found: error

  package-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Create Python executable zip
        run: zip -j launcher-py.zip src/launcher/*.py

      - name: Elevate script permissions
        run: |
          chmod +x src/launcher/launch.sh

      - name: Create release zip
        run: zip -j ZenithProxy-launcher-python.zip launcher-py.zip src/launcher/requirements.txt src/launcher/launch.sh src/launcher/launch.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-python
          path: ZenithProxy-launcher-python.zip
          if-no-files-found: error

      - name: Get Binary Hash
        run: sha1sum -b launcher-py.zip | cut -d" " -f 1 > ZenithProxy-launcher-python.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v4
        with:
          name: launcher-python.sha1
          path: ZenithProxy-launcher-python.sha1
          if-no-files-found: error

  # same as python package but with a custom bat script that bootstraps the python interpreter
  package-windows-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Create Python executable zip
        run: zip -j launcher-py.zip src/launcher/*.py

      - name: Rename launch_windows.bat
        run: cp src/launcher/launch_windows.bat launch.bat

      - name: Create release zip
        run: zip -j ZenithProxy-launcher-windows-python-amd64.zip launcher-py.zip src/launcher/requirements.txt launch.bat scripts/windows_help.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-windows-python-amd64
          path: ZenithProxy-launcher-windows-python-amd64.zip
          if-no-files-found: error

      - name: Get Binary Hash
        run: sha1sum -b launcher-py.zip | cut -d" " -f 1 > ZenithProxy-launcher-windows-python-amd64.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v4
        with:
          name: launcher-windows-python-amd64.sha1
          path: ZenithProxy-launcher-windows-python-amd64.sha1
          if-no-files-found: error

  release-artifacts:
    needs:
      - build-matrix
      - build-alpine
      - package-python
      - package-windows-python
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Download job artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts/

      - name: Compile Hashes
        run: |
          cat artifacts/**/*.sha1 > hashes.txt

      - name: Upload Hashes Version
        uses: actions/upload-artifact@v4
        with:
          name: hashes.txt
          path: hashes.txt
          if-no-files-found: error
