name: ZenithProxy Build

on:
  pull_request:
  push:
    branches:
      - "1.21.4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build ZenithProxy
        run: ./gradlew build

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload Java Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ZenithProxy-java
          path: build/libs/ZenithProxy.jar
          if-no-files-found: error
          archive: false
