name: Build Launcher

on:
  workflow_dispatch:

jobs:
  build-windows-amd64:
    runs-on: 'windows-2019'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: |
          pip install -U pyinstaller
        shell: pwsh

      - name: Build launcher
        run: |
          pyinstaller --specpath .\build -p .\src\launcher --onefile --noconfirm .\src\launcher\main.py
        shell: pwsh

      - name: Rename executable
        run: |
          Move-Item -Path .\dist\main.exe -Destination .\dist\launcher.exe
        shell: pwsh

      - name: Create zip
        run: |
          Compress-Archive -Path .\dist\launcher.exe -DestinationPath .\dist\ZenithProxy-launcher-windows-amd64.zip
        shell: pwsh

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: launcher-windows-amd64
          path: dist/ZenithProxy-launcher-windows-amd64.zip

  build-linux-amd64:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: |
          pip install -U pyinstaller

      - name: Build launcher
        run: |
          pyinstaller --specpath ./build -p ./src/launcher --onefile --noconfirm ./src/launcher/main.py

      - name: Rename executable
        run: |
          mv dist/main dist/launcher

      - name: Elevate binary permissions
        run: chmod +x dist/launcher

      - name: Create zip
        run: zip -j dist/ZenithProxy-launcher-linux-amd64.zip dist/launcher

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: launcher-linux-amd64
          path: dist/ZenithProxy-launcher-linux-amd64.zip

  build-linux-aarch64:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binary on emulated aarch64
        run: |
          docker run --rm --platform linux/arm64 --volume "${PWD}:/repo" python:3.12-bullseye /bin/sh -c " \
            cd /repo && \
            python3 -m pip install -U pyinstaller && \
            pyinstaller --specpath ./build -p ./src/launcher --onefile --noconfirm ./src/launcher/main.py
          "

      - name: Rename executable
        run: |
          sudo mv dist/main dist/launcher

      - name: Elevate binary permissions
        run: sudo chmod +x dist/launcher

      - name: Create zip
        run: sudo zip -j dist/ZenithProxy-launcher-linux-aarch64.zip dist/launcher

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: launcher-linux-aarch64
          path: dist/ZenithProxy-launcher-linux-aarch64.zip

  build-mac-amd64:
    runs-on: 'macos-11'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: |
          pip install -U pyinstaller

      - name: Build launcher
        run: |
          pyinstaller --specpath ./build -p ./src/launcher --onefile --noconfirm ./src/launcher/main.py

      - name: Rename executable
        run: |
          mv dist/main dist/launcher

      - name: Elevate binary permissions
        run: chmod +x dist/launcher

      - name: Create zip
        run: zip -j dist/ZenithProxy-launcher-macos-amd64.zip dist/launcher

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: launcher-macos-amd64
          path: dist/ZenithProxy-launcher-macos-amd64.zip

  release-artifacts:
    needs:
      - build-windows-amd64
      - build-linux-amd64
      - build-linux-aarch64
      - build-mac-amd64
    runs-on: ubuntu-20.04
    steps:
      - name: Download job artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/
      - name: Publish Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "launcher-v3"
          artifacts: artifacts/*.zip
          allowUpdates: true
          replacesArtifacts: true
          omitBodyDuringUpdate: true
#          makeLatest: true
