name: 1.21.4 PreRelease Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+1.21.4.pre'

jobs:
  build-java-and-linux-amd64:
    # 32gb memory needed for instrumenting
    runs-on: ubicloud-standard-8
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Versions and Paths
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Get Release Tags
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          j_tag="$(sed 's/\+/\+java./' <<< $TAG_NAME)"
          echo "JAVA_TAG=$j_tag" >> "$GITHUB_ENV"
          l_tag="$(sed 's/\+/\+linux./' <<< $TAG_NAME)"
          echo "LINUX_TAG=$l_tag" >> "$GITHUB_ENV"
        shell: bash

      - name: Export Java Tag
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "RELEASE_TAG=$JAVA_TAG" >> "$GITHUB_ENV"

      - name: Build ZenithProxy Java
        run: ./gradlew build -x test

      - name: Upload Java Artifact
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/ZenithProxy.jar
          if-no-files-found: error
          archive: false

      - name: Download GraalVM Profile
        run: |
          wget https://cdn.2b2t.vc/profile.iprof
          echo "GRAALVM_PGO_PATH=$(pwd)/profile.iprof" >> "$GITHUB_ENV"

      - name: Enable GraalVM Build Report
        run: echo "GRAALVM_BUILD_REPORT=true" >> "$GITHUB_ENV"

#      - name: Enable GraalVM Profile Instrumenting
#        run: |
#          echo "GRAALVM_PGO_INSTRUMENT=true" >> "$GITHUB_ENV"

      - name: Export Linux Tag
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "RELEASE_TAG=$LINUX_TAG" >> "$GITHUB_ENV"

      - name: Build ZenithProxy Linux Native
        run: ./gradlew nativeCompile -x test

      - name: Move GraalVM Build Report
        run: mv build/native/nativeCompile/*build-report.html build/native/ZenithProxy-build-report.html

      - name: Elevate binary permissions
        run: chmod +x build/native/nativeCompile/*

      - name: Zip Binary And Libs
        run: zip -j ZenithProxy.zip build/native/nativeCompile/*

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v7
        with:
          path: ZenithProxy.zip
          if-no-files-found: error
          archive: false

      - name: Upload GraalVM Build Report
        uses: actions/upload-artifact@v7
        with:
          name: GraalVM Build Report
          path: build/native/ZenithProxy-build-report.html
          if-no-files-found: error
          archive: false

      - name: Publish Maven Artifact Snapshot
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publishSnapshotPublicationToSnapshotsRepository

  release-artifacts:
    needs:
      - build-java-and-linux-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Download java artifact
        uses: actions/download-artifact@v8
        with:
          name: ZenithProxy.jar
          merge-multiple: true
          path: artifacts/

      - name: Download linux artifact
        uses: actions/download-artifact@v8
        with:
          name: ZenithProxy.zip
          merge-multiple: true
          path: artifacts/
          skip-decompress: true

      - name: Get Release Tags
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          j_tag="$(sed 's/\+/\+java./' <<< $TAG_NAME)"
          echo "JAVA_TAG=$j_tag" >> "$GITHUB_ENV"
          l_tag="$(sed 's/\+/\+linux./' <<< $TAG_NAME)"
          echo "LINUX_TAG=$l_tag" >> "$GITHUB_ENV"

      - name: Publish Java Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.JAVA_TAG }}
          artifacts: "artifacts/*.jar"
          prerelease: true
          body: "File upload not for users. **Use the Launcher:** https://github.com/rfresh2/ZenithProxy/releases/tag/launcher-v3"
          commit: ${{ github.sha }}
          artifactErrorsFailBuild: true

      - name: Publish Linux Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LINUX_TAG }}
          artifacts: "artifacts/ZenithProxy.zip"
          prerelease: true
          body: "File upload not for users. **Use the Launcher:** https://github.com/rfresh2/ZenithProxy/releases/tag/launcher-v3"
          commit: ${{ github.sha }}
          artifactErrorsFailBuild: true
