name: Release Launcher

on:
  workflow_dispatch:

env:
  UV_PYTHON: '3.14.4'
  pyinstaller_version: "6.19.0"

jobs:
  backup-existing:
    runs-on: ubuntu-latest
    steps:
      - name: Download current launcher files
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          tag: launcher-v3
          fileName: "*"
          out-file-path: launcher-assets

      - name: Zip launcher assets
        run: zip -j -r launcher-assets.zip launcher-assets/

      - name: Upload assets
        uses: actions/upload-artifact@v7
        with:
          name: existing-launcher-assets
          path: launcher-assets.zip
          if-no-files-found: error
          archive: false

  build-pyinstaller:
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image || '' }}
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-15' ]
        include:
          - os: 'ubuntu-latest'
            image: 'catthehacker/ubuntu:act-20.04'
            artifact-name: 'launcher-linux-amd64'
            sha1-command: 'sha1sum -b dist/launch | cut -d" " -f 1'
          - os: 'ubuntu-24.04-arm'
            image: 'catthehacker/ubuntu:act-20.04'
            artifact-name: 'launcher-linux-aarch64'
            sha1-command: 'sha1sum -b dist/launch | cut -d" " -f 1'
          - os: 'macos-15-intel'
            artifact-name: 'launcher-macos-amd64'
            sha1-command: 'shasum dist/launch | cut -d" " -f 1'
          - os: 'macos-15'
            artifact-name: 'launcher-macos-aarch64'
            sha1-command: 'shasum dist/launch | cut -d" " -f 1'
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install PyInstaller
        run: |
          uv tool install pyinstaller@${{ env.pyinstaller_version }}

      - name: Build launcher
        run: >
          uv tool run --with-requirements src/launcher/requirements.txt --upgrade
          pyinstaller@${{ env.pyinstaller_version }} --specpath ./build
          -p ./src/launcher --onefile
          --runtime-tmpdir .launcher.tmp
          --noconfirm
          -i ../src/launcher/icon.ico
          ./src/launcher/__main__.py

      - name: Rename executable
        run: |
          mv dist/__main__ dist/launch

      - name: Create zip
        run: |
          zip -j dist/ZenithProxy-${{ matrix.artifact-name }}.zip dist/launch

      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/ZenithProxy-${{ matrix.artifact-name }}.zip
          if-no-files-found: error
          archive: false

      - name: Get Binary Hash
        run: ${{ matrix.sha1-command }} > ZenithProxy-${{ matrix.artifact-name }}.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-name }}.sha1
          path: ZenithProxy-${{ matrix.artifact-name }}.sha1
          if-no-files-found: error
          archive: false

  build-alpine:
    env:
      pyinstaller_version: "6.18.0"
      UV_PYTHON: '3.14.2'
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image || '' }}
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-24.04-arm']
        include:
          - os: 'ubuntu-latest'
            image: 'node:24-alpine3.23'
            artifact-name: 'launcher-alpine-amd64'
            sha1-command: 'sha1sum -b dist/launch | cut -d" " -f 1'
          - os: 'ubuntu-24.04-arm'
            image: 'node:24-alpine3.23'
            artifact-name: 'launcher-alpine-aarch64'
            sha1-command: 'sha1sum -b dist/launch | cut -d" " -f 1'
    steps:
      # https://github.com/dart-musl/setup-node-alpine-for-javascript-actions
      - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
        run: |
          if grep -q '^ID=alpine$' /etc/os-release; then
            ROOT=$(TMPDIR="$RUNNER_TEMP" mktemp -d)
            apk add --root "$ROOT" --repositories-file /etc/apk/repositories --allow-untrusted --no-cache --no-scripts --initdb -- docker-cli
            "$ROOT/usr/bin/docker" run --rm --net host --user 0:0 --volume /:/hostfs --entrypoint /usr/sbin/chroot "$("$ROOT/usr/bin/docker" inspect '${{ job.container.id }}' --format "{{ .Image }}")" /hostfs /bin/bash -xc \
              'exec sudo -u "$(stat -c "%U" -- "$7")" -- /bin/bash -xc "$@"' -- \
              'find "$5" -type f -executable -name node -not -path "*_alpine/*" -print0 | exec xargs -0 -n 1 -- /bin/bash -xc "$@"' -- \
              'exec docker run --rm --volume /:/hostfs --entrypoint /bin/sh "docker.io/library/node:$("$4" -e "console.log(process.versions.node)")-alpine" -xc "$@"' -- \
              'apk add --no-cache -- patchelf && apk info --quiet --contents -- libgcc libstdc++ | xargs -- tar -cC / -T- | tar -xvC "$(dirname "/hostfs$2")/../lib" --strip-components 2 && cp "$(which node)" "/hostfs$2" && patchelf --set-rpath \$ORIGIN/../lib "/hostfs$2" && ldd "/hostfs$2"' -- \
              "$("$ROOT/usr/bin/docker" inspect '${{ job.container.id }}' --format '{{ range.Mounts }}{{ if eq .Destination "/__e" }}{{ .Source }}{{ end }}{{ end }}')"
            rm -rf -- "$ROOT"
            sed -i -e 's/^ID=alpine$/ID=linux/' /etc/os-release
          fi
        shell: sh

      - name: Install Deps
        run: apk add zip bash build-base ca-certificates curl gcc git libc-dev libffi-dev libgcc make musl-dev openssl openssl-dev zlib-dev

      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install PyInstaller
        run: |
          uv tool install pyinstaller@${{ env.pyinstaller_version }}

      - name: Build launcher
        run: >
          uv tool run --with-requirements src/launcher/requirements.txt --upgrade
          pyinstaller@${{ env.pyinstaller_version }} --specpath ./build
          -p ./src/launcher --onefile
          --runtime-tmpdir .launcher.tmp
          --noconfirm
          -i ../src/launcher/icon.ico
          ./src/launcher/__main__.py

      - name: Rename executable
        run: |
          mv dist/__main__ dist/launch

      - name: Create zip
        run: |
          zip -j dist/ZenithProxy-${{ matrix.artifact-name }}.zip dist/launch

      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/ZenithProxy-${{ matrix.artifact-name }}.zip
          if-no-files-found: error
          archive: false

      - name: Get Binary Hash
        run: ${{ matrix.sha1-command }} > ZenithProxy-${{ matrix.artifact-name }}.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-name }}.sha1
          path: ZenithProxy-${{ matrix.artifact-name }}.sha1
          if-no-files-found: error
          archive: false


  package-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create Python executable zip
        run: zip -j launcher-py.zip src/launcher/*.py

      - name: Elevate script permissions
        run: |
          chmod +x src/launcher/launch.sh

      - name: Create release zip
        run: zip -j ZenithProxy-launcher-python.zip launcher-py.zip src/launcher/requirements.txt src/launcher/launch.sh src/launcher/launch.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: launcher-python
          path: ZenithProxy-launcher-python.zip
          if-no-files-found: error
          archive: false

      - name: Get Binary Hash
        run: sha1sum -b launcher-py.zip | cut -d" " -f 1 > ZenithProxy-launcher-python.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v7
        with:
          name: launcher-python.sha1
          path: ZenithProxy-launcher-python.sha1
          if-no-files-found: error
          archive: false

  # same as python package but with a custom bat script that bootstraps the python interpreter
  package-windows-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create Python executable zip
        run: zip -j launcher-py.zip src/launcher/*.py

      - name: Rename launch_windows.bat
        run: cp src/launcher/launch_windows.bat launch.bat

      - name: Create release zip
        run: zip -j ZenithProxy-launcher-windows-python-amd64.zip launcher-py.zip src/launcher/requirements.txt launch.bat scripts/windows_help.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: launcher-windows-python-amd64
          path: ZenithProxy-launcher-windows-python-amd64.zip
          if-no-files-found: error
          archive: false

      - name: Get Binary Hash
        run: sha1sum -b launcher-py.zip | cut -d" " -f 1 > ZenithProxy-launcher-windows-python-amd64.sha1

      - name: Upload Launcher Hash Version
        uses: actions/upload-artifact@v7
        with:
          name: launcher-windows-python-amd64.sha1
          path: ZenithProxy-launcher-windows-python-amd64.sha1
          if-no-files-found: error
          archive: false

  release-artifacts:
    needs:
      - build-pyinstaller
      - build-alpine
      - package-python
      - package-windows-python
    runs-on: ubuntu-latest
    steps:
      - name: Download job artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: artifacts/

      - name: Remove old launcher assets
        run: rm artifacts/launcher-assets.zip

      - name: Compile Hashes
        run: |
          cat artifacts/*.sha1 > hashes.txt

      - name: Upload hashes.txt
        uses: actions/upload-artifact@v7
        with:
          name: hashes
          path: hashes.txt
          if-no-files-found: error
          archive: false

      - name: Publish Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "launcher-v3"
          artifacts: "artifacts/*.zip,hashes.txt"
          name: "Launcher V3"
          allowUpdates: true
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
          makeLatest: true
          artifactErrorsFailBuild: true

      - name: Docker Update
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DOCKER_REPO_TOKEN }}
          repository: rfresh2/ZenithProxyDocker
          event-type: launcher-release
